### ISSUE TITLE
ability to log work on an issue that is not assigned to me

### ISSUE THREAD

**Issue by lordang** [gioboa/jira-plugin#100]
**Is your feature request related to a problem? Please describe.**
We don't change assignee when transition to 'in review" status occur.
So our code reviewer just log their review work on an issue assigned to developer.
And I prefer reviewing on vscode using something like gitlens plugin.

Now when I click on "Set working issue" button, it seems working issue list only shows issues assigned to me.
So some options menu is needed to list issues that are not assigned to me.

**Describe the solution you'd like**
I suggest making setting option menu like "jira-plugin: Working Issue Assignee" to set working issue assignee below "jira-plugin: working Issue Statuses" menu.
So that user can choose filtered assignee.
I think two option(me or all) is enough.

**Describe alternatives you've considered**

**Additional context**
screens related this feature request
![image](https://user-images.githubusercontent.com/921803/54264763-2561aa00-45b7-11e9-9eef-8c93efeb455d.png)
![image](https://user-images.githubusercontent.com/921803/54264791-33afc600-45b7-11e9-8c6d-80294dca6ccd.png)

**Comment by gioboa** [comment]
Hi @lordang ,
the plugin perform this JQL 
`project = '${project}' AND status in (${statuses}) AND assignee in (currentUser()) ORDER BY status ASC, updated DESC`
so as you suggest we can add additional configuration to customize assignee values.
Thanks for your feedback. 👍
