### ISSUE TITLE
feat: Hide seconds on worked time clock

### ISSUE THREAD

**Issue by Psidium** [gioboa/jira-plugin#103]
Great extension! This extension removes a big headache in our team: time tracking.

**Is your feature request related to a problem? Please describe.**
I don't like that the time tracking shows the seconds worked on the issue. Feels like a time 💣.

**Describe the solution you'd like**
Ability to hide the seconds and the minutes worked on an issue on the clock on the lower left bar, configured via the extension settings.

I consider this just to be a cosmic change, if I were to classify, I'd say it's a minor issue.

**Comment by gioboa** [comment]
I will implement it in the next release. :+1:
