### ISSUE TITLE
feat: ability to start progress on any issue

### ISSUE THREAD

**Issue by caleb15** [gioboa/jira-plugin#104]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't start work on a issue because it's not in progress. Sometimes I might want to add work on a in review issue. Also it would be nice if working on a issue automatically moved it to in progress (if lets say it was in to do initially).

**Describe the solution you'd like**
When I click on working issue I should be able to search for any issue, with the ones in progress appearing at the top of the search results initially.

**Describe alternatives you've considered**
Make the issue in progress and then work on it.

**Additional context**

Just a minor issue, thanks for the working issue feature! It's useful to track my hours.

**Comment by gioboa** [comment]
Hi @caleb15 ,
if you want also review issue there is the specific setting for it `Working Issue Statues` .
Implement move automatically `in progress` can be difficult because every team as different workflow.
We need to think a universal way to do that, maybe a setting or something like this.

**Comment by gioboa** [comment]
A solution can be a setting to enable/disable this feature:
- after working issue selection the plugin call `change status` for that issue, then the user will decide the new status or skip the change. You can change into `in progress` or something else. @caleb15 what do you think?
