### ISSUE TITLE
Can't define password in parameters

### ISSUE THREAD

**Issue by patrick-mota** [gioboa/jira-plugin#105]
**Describe the issue**
If you configure jira plugin via the parameters menu you can't define the password since the field doesn't exist.

**To Reproduce**

1. Go to Parameters
2. Click on Extensions
2. Click on Jira configuration
3. Scroll down to username
4. Can't find password input

**Expected behavior**
I think we should be able to define the password from the parameters and not only from the command line ">jira-plugin:reset credentials"
Maybe isn't considered as an issue since you say in your doc to go through the command to configure jira plugin.

**Comment by gioboa** [comment]
Hi @patrick-mota , 
password field is hidden for security reason. 
The only way to configure it is by `setup credential` command.
The plugin store password data inside VsCode global storage.
The system for store this info use the combination of baseUrl + user , so you can have different combinations as expected. :+1:

**Comment by patrick-mota** [comment]
Ah ok, thank you for your fast answer.

I asked because usually in some plugins we have a button to set a password with hidden chars.

Btw thank you for your plug-in he is awesome.

Just one or two missing features like seeing the issue directly in vs code and the most important for me would be to manage time manually (like a start/stop button) and not only when you switch in issues but I'll try to contribute something about this.

**Comment by gioboa** [comment]
Seeing issues directly in VsCode is something interesting but it's hard to manage all the fields and situations. Add stop/start button can be quite simple to implement. If you like you can create a PR for it. :+1:
