### ISSUE TITLE
issue: Splitting on CREDENTIALS_SEPARATOR can Break Authentication

### ISSUE THREAD

**Issue by aglensmith** [gioboa/jira-plugin#106]
**Describe the issue**

Its possible for password or username to contain `CREDENTIALS_SEPARATOR`. When this happens, authentication breaks. 

**To Reproduce**

1. During configuration, enter password or username that contains `CREDENTIALS_SEPARATOR`.
2. place breakpoint [here](https://github.com/gioboa/jira-plugin/blob/develop/src/services/configuration.service.ts#L35)
3. Run
4. username or password missing characters

** Recommendation **

* Base64 encode credentials before storage, or
* Add setting for custom separator, or
* Add functionality to pull credentials from environment variable, or
* Add functionality for entering base64 encoded credentials

**Comment by gioboa** [comment]
Hi,
nice catch. :+1:
If you want you can create a PR or if you prefer I will solve the issue. 
Thanks. :+1:

**Comment by gioboa** [comment]
I solved the issue.
The plugin stored credentials in JSON format. 
If JSON.parse fail I assume the credentials were store by a previous version.

**Comment by gioboa** [comment]
@aglensmith  
I solved the issue by my own, but if you want to contribute in something, you are welcome. 😄 👍
