### ISSUE TITLE
issue: can't set working issue

### ISSUE THREAD

**Issue by RafeSafari** [gioboa/jira-plugin#107]
I was trying to set the working issue from here:
![image](https://user-images.githubusercontent.com/8758127/56263710-4313b900-60f9-11e9-9e1a-44436a838c92.png)

Encountered with message:
![image](https://user-images.githubusercontent.com/8758127/56263751-735b5780-60f9-11e9-9067-994d9f7b31d5.png)

I'm logged in, and the project IQEY is selected, also there are issues in IQEY project which are assigned to me:
![image](https://user-images.githubusercontent.com/8758127/56263950-29bf3c80-60fa-11e9-8e95-d7534d9fb2c9.png)

But no luck fetching the issues

**Comment by gioboa** [comment]
Hi, in 138 and 120 status is 'in progress'?
If not, you can customize the working issue statuses in settings. :+1:

**Comment by RafeSafari** [comment]
I tried this:
![image](https://user-images.githubusercontent.com/8758127/56265106-e2d34600-60fd-11e9-8c7f-c28e5669794f.png)

and this:
![image](https://user-images.githubusercontent.com/8758127/56265138-fb436080-60fd-11e9-8912-b1d4472b5d36.png)

still the same info message!
![image](https://user-images.githubusercontent.com/8758127/56265204-304fb300-60fe-11e9-909d-e19afe67c6f0.png)

**Comment by gioboa** [comment]
The plugin perform this JQL for retrieving the issues.
`project = '${project}' AND status in (${statuses}) AND assignee in (${assignees}) ORDER BY status ASC, updated DESC`
If you perform this jql in Jira web application, have you got any result?

**Comment by RafeSafari** [comment]
thanks for the reply,
`project = 'IQEY' AND status in ("In Progress") AND assignee in ('rafe') ORDER BY status ASC, updated DESC`
found nothing, but 
`project = 'IQEY' AND statusCategory in ("In Progress") AND assignee in ('rafe') ORDER BY status ASC, updated DESC`
works like charm!
So, how should I change the JQL in vsCode plugin?

**Comment by gioboa** [comment]
At the moment there isn't possibility to change working issue JQL. You can customise statuses, assignees but not the fields. 😢 
So in you environment there is difference from status and statusCategory.
You can try by adding all statuses assigned to statusCategory 'In progress'.

**Comment by RafeSafari** [comment]
> You can try by adding all statuses assigned to statusCategory 'In progress'.
Is there any tutorial web page to do the adding?

**Comment by gioboa** [comment]
[here](https://github.com/gioboa/jira-plugin#settings)
- **Working Issue Statues** <br>
  Statuses used for extract working issue list (e.g. In Progress, Development In Progress, Test in Progress)
You can find this setting in VsCode :+1:

**Comment by RafeSafari** [comment]
Added working issue status and it's working great!
Closing...
Thanks
