### ISSUE TITLE
Jira Atlassian v74.5 and https: impossible to connect

### ISSUE THREAD

**Issue by magneticcore** [gioboa/jira-plugin#108]
We use Jira internally with a proxy.
Visual Sudio Code: 1.33.1, Windows version
Jira-Plugin: 0.16.0

After switching to Jira v7.4.5 and using https in place of http for the Jira server, Jira Plugin cannot anymore connect to our Jira server (before with old Jira server version and http, all was worked as expected and great).

Now Jira-Plugin gives the following error:
Error: Check Jira Plugin settings in VSCode
TypeError: cannot read property 'status' of undefined

the following settings are in use in VSCode:
http.proxy: https://ourproxy
http.proxyStrictSSL: false
jira-plugin.baseUrl: https://jiraserver
jira-plugin.strictSSL: false

I cannot find anything to resolve this problem.
Thank you for your help

**Comment by gioboa** [comment]
Hi @magneticcore , did you try by adding some statuses in `additional stutuses` setting?

**Comment by magneticcore** [comment]
Hi gioboa,
Thank you for your quick answer.

There is no additional status in jira-plugin settings.
Is these additional status match jira state or status?
If yes, there is no new visible jira state in Jira server v7.4.5 comparing to our previous version. But I need to check with an administrator.
If no, what it is exactly?

**Comment by gioboa** [comment]
With this special setting you can add custom status e.g Done, In progress and the plugin will use them. Try to set Done, In progress, To do and check the result.

**Comment by magneticcore** [comment]
I put a lot of jira status separated by comma (English and french) as you told me but still the same, error. 
I wrote them like yours,, Done and not done.
The list: Done,In Progress,No Category,To Do,Opened,Reopened,Resolved,Closed,In Creation,Affected,Rejected,Ready,New,Ready for Version

Is there a possibility to know which status is missing?

**Comment by gioboa** [comment]
Maybe it's another problem.
Firt of first, do you see issue list correctly?

**Comment by magneticcore** [comment]
No list of issues. In fact, nothing. After opening VS Code, the jira-plugin raises the error directly. That's why I thought about connection problem.

**Comment by gioboa** [comment]
The fastest way to understand the problem is hack the plugin code.
Are you on Windows or Mac/Linux environment?

**Comment by ChrisKader** [comment]
@magneticcore  I noticed you said you are using a self hosted JIRA.

@gioboa does this plugin work with self-hosted solutions?

**Comment by gioboa** [comment]
Yes, It work correctly with environment hosted in self domain. e.g https://jira.xxx.com :+1:

**Comment by gioboa** [comment]
@magneticcore Did you find something? did you manage to debug the code?

**Comment by gioboa** [comment]
Yes, you are right, if the plugin is not configured yet I will hide the error.

**Comment by gioboa** [comment]
@magneticcore 
I looked in the code and the error appear also when credentials are wrong.
Did you try to setup credentials from zero?

**Comment by gioboa** [comment]
@magneticcore Do you have some news?
