### ISSUE TITLE
feat: settings: Projects To Include

### ISSUE THREAD

**Issue by mrmikee** [gioboa/jira-plugin#109]
Instead of only being allowed to Exclude projects, please add feature to only Include projects in a "white list".  

Our team shares a JIRA self-hosted instance with 30+ other teams and the Exclude list would be too large to manage.  Being able to only include the 5-10 projects we actually work on would be a great help.

**Comment by gioboa** [comment]
hi @mrmikee,
this issue is related to #91 , please have a look. :+1:

**Comment by gioboa** [comment]
In v 0.19.0 I added projectsToShow setting. Here you can define only the projects to include. The plugin keep, from all project list, only the project keys you define.
