### ISSUE TITLE
Impossible to login to jira cloud

### ISSUE THREAD

**Issue by drpark** [gioboa/jira-plugin#110]
Hi,
i'm using jira in cloud mode via https://mycompany.atlassian.net
i set the credentials correctly, but i get a "check log in jira terminal output" but so i don't have the jira logs because of using jira cloud...

Is it possible to connect successfully on a jira cloud account?

thank you

**Comment by gioboa** [comment]
Hi @drpark,
[here](#34) you can find the logs.

**Comment by drpark** [comment]
ok thank you, didn't understood it was an api token needed. Works ok.
