### ISSUE TITLE
No STATUS: 'In progress', ASSIGNEES: currentUser() issues found in [project-name] project

### ISSUE THREAD

**Issue by juanfernandes** [gioboa/jira-plugin#111]
When I click on "No working issue" on the status bar, i get the following message:
> No STATUS: 'In progress', ASSIGNEES: currentUser() issues found in EFT project

_This is most likely an issue with our setup._

**To Reproduce**
1. Make sure you're in a Project, without an issue selected
1. Click on 'No working issue'

**Expected behaviour**
It should allow me to choose an issue to work on

**Desktop (please complete the following information):**
> Version: 1.35.1 (user setup)
> Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
> Date: 2019-06-12T14:30:02.622Z
> Electron: 3.1.8
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.16299

**Log**
_Nothing in the log_

**Comment by gioboa** [comment]
Hi, 
Have you got any issues in Jira web application for your user with status in progress?

**Comment by FelikZ** [comment]
I have the same issue. Updated setting called "Jira-plugin: Working Issue Statues" to a proper list of statuses that I am interested in:
`"In Progress","To Do","Review"`
However, it still show the same query with `In progress`, regardless of window reload.

**Comment by gioboa** [comment]
@FelikZ great to see that it's resolved. 👍
