### ISSUE TITLE
feat: Show Jira Issue# after creating new issue

### ISSUE THREAD

**Issue by PDunbarCGI** [gioboa/jira-plugin#112]
**Is your feature request related to a problem? Please describe.**
When I create a new issue, I typically have to open the issue in a browser in order to see it.  

**Describe the solution you'd like**
Really, it would be nice if the message completion dialog displayed the newly created issue ID and offered to make it my working issue if I didn't have an active one at the moment.

**Comment by gioboa** [comment]
Hi @PDunbarCGI 
It's quite easy and I will implement it :+1: :smile:
