### ISSUE TITLE
feat: jira query timeout

### ISSUE THREAD

**Issue by gchr** [gioboa/jira-plugin#114]
**Is your feature request related to a problem? Please describe.**
Our JIRA server is slow. Most of the queries end up with a ESOCKETTIMEDOUT in "JIRA-PLUGIN" output

**Describe the solution you'd like**
A setting defining the response timeout when quering Jira server.

**Describe alternatives you've considered**
An increase to the default timeout.

**Comment by gioboa** [comment]
Hi @gchr,
Thanks for your feedback.
I will check if there is the possibility to create a param for query timeout :+1:

**Comment by MrRefactoring** [comment]
I think this behavior should be implemented in the `jira-connector`. I'm right?

**Comment by gioboa** [comment]
@MrRefactoring yes, I did check if `jira-connector` accept timeout param.
If the lib implement this feature, the code can be much cleaner 👍

**Comment by MrRefactoring** [comment]
Timeout added in version 2.15.2 (jira-connector)

**Comment by MrRefactoring** [comment]
Example:

```js
new JiraClient({
  host: 'xxx.atlasian.com',
  timeout: 10000 // 10 seconds
});
```

**Comment by gioboa** [comment]
Great news. 🥇 I will update the lib and I will add the param in the plugin settings

**Comment by gchr** [comment]
Great job guys! @gioboa @MrRefactoring 
Thanks!
