### ISSUE TITLE
Trying to get Default JQL Search working

### ISSUE THREAD

**Issue by dthielking** [gioboa/jira-plugin#115]
**Describe the issue**
Hello, I'm new to this extension. Maybe I make something wrong.
I want to create my own JQL Search. I constructed it via Jiras search and tried pasting it in the appropriate config. 
But it seems that this is not working.

I want to see all issues assigned to me with status open in the current sprint.
`sprint in openSprints() and sprint not in futureSprints() AND status = OPEN  AND assignee in (currentUser()) ORDER BY status ASC, updated ASC`
I get all issues with status open.

**Expected behavior**
Get only what the JQL search specifies or an error when not able to satisfy

**Desktop (please complete the following information):**

Version: Version 1.35.1 (1.35.1)

**Comment by gioboa** [comment]
Hi @dthielking ,
the plugin already search for current sprint with this JQL: 

`project = '${project}' AND sprint in openSprints() and sprint not in futureSprints() ORDER BY status ASC, updated ASC`

maybe you can simply add `AND status = OPEN AND assignee in (currentUser())` at the above JQL
please have a try 👍

**Comment by dthielking** [comment]
Hi @gioboa i did that and it didn't work.
I see all open jira issues.

**Comment by gioboa** [comment]
And the same JQL extract different issues in Jira Web Application?

**Comment by dthielking** [comment]
Yes.
`sprint in openSprints() and sprint not in futureSprints() AND status = OPEN AND assignee in (currentUser()) ORDER BY status ASC, updated ASC` in Jira itself gives me exactly what I except.

**Comment by gioboa** [comment]
Could you tell me in witch param you have insert the JQL please?

**Comment by dthielking** [comment]
Yes of course.
`"jira-plugin.defaultJqlSearch": "project = '${project}' AND sprint in openSprints() and sprint not in futureSprints() ORDER BY status ASC, updated ASC"`
This is the entry in my `settings.json`.

**Comment by gioboa** [comment]
Ok, so this search is available in the three dots menu. 
In this JQL I don't see any filter for you user...
You need a VsCode restart for apply new changes in the plugin settings.

**Comment by dthielking** [comment]
Thank you for the hint with restarting.
Now I'm using the correct JQL.
`"jira-plugin.defaultJqlSearch": "project = '${project}' AND sprint in openSprints() and sprint not in futureSprints() AND status = OPEN AND assignee in (currentUser()) ORDER BY status ASC, updated ASC",`

And after restarting VSCode I get an error from the JIRA-PLUGIN Output Terminal.
`{"statusCode":400,"body":{"errorMessages":["The value '${project}' does not exist for the field 'project'."],'

**Comment by gioboa** [comment]
Here the description of default jql settings
"description": "Here you can define your default/custom JQL search (n.b: WORKING_PROJECT is the placeholder for the current working project)"

The default value:
 "project = 'WORKING_PROJECT' ORDER BY status ASC, updated DESC"

So replace project piece with this project = 'WORKING_PROJECT' :+1:

**Comment by dthielking** [comment]
Great. Thank you for your help!
Now it works! 😀

**Comment by dcarreraccc** [comment]
Hi @gioboa it would be nice if in the description of that parameter you specify that you need a VSCode Reload for the new default JQL search to work.

**Comment by gioboa** [comment]
Thanks for the suggestion @dvonessen 👍
