### ISSUE TITLE
Problem with work log submitting

### ISSUE THREAD

**Issue by QuercusB** [gioboa/jira-plugin#118]
**Problem:**
When trying to submit work log got a error in "Jira Plugin" output window.
However, it actually worked week ago and I suspect that our Jira masters have changed something in Jira. If I go to issue in Jira I'm able to add work log.

Truncated error:

`{"statusCode":400,"body":{"errorMessages":["Unrecognized field \"worklog\" (Class com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@3b2fb883; line: 1, column: 13] (through reference chain: com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean[\"worklog\"])"]}....`

**To Reproduce**

1. Select working issue
2. Wait for some time, then deselect it
3. See add work log dialog, press 'Add' button

**Expected behavior**
Expected work log to be added to Jira issue.

**Desktop (please complete the following information):**
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Log**
{"statusCode":400,"body":{"errorMessages":["Unrecognized field \"worklog\" (Class com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@3b2fb883; line: 1, column: 13] (through reference chain: com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean[\"worklog\"])"]}

**Comment by gioboa** [comment]
Hi, with previous version works?

**Comment by QuercusB** [comment]
Previous version of plugin?
Didn't notice that plugin was updated.

It worked a week ago (maybe even two days ago) - something changed since then.

**Comment by gioboa** [comment]
Yes, I updated the plugin a day ago.
I think this [commit](https://github.com/floralvikings/jira-connector/commit/e359449ddf699747d2cce0bedf9f5438a873d084#diff-86e3970419724dabc12f35fb7aca98f7) broke something. 
You can downgrade the plugin version and I will fix as soon as possible. Thanks.

**Comment by QuercusB** [comment]
Thanks, downgraded - that helps.

**Comment by gioboa** [comment]
In the new [v 0.18.1](https://github.com/gioboa/jira-plugin/releases/tag/0.18.1) works as expected. 👍
