### ISSUE TITLE
Support for API key authentication

### ISSUE THREAD

**Issue by kahyoung** [gioboa/jira-plugin#12]
👋 This extension looks great but I can't use it at my workplace. We authenticate using Google OAuth, so we don't really have an email and password to attach.

Would love to be able to use API keys though.

I can have a look at this later on and see if I can make a PR.

**Comment by gioboa** [comment]
I created a new branch "jira-connector", it's for remove custom Jira calls and use "jira-connector" [npm](https://www.npmjs.com/package/jira-connector). With this package we have Base and OAuth Authentication. :+1:

**Comment by gioboa** [comment]
In this [branch](https://github.com/gioboa/jira-plugin/tree/jira-connector) I replace custom API Calls with jira-connection. In this [commit](https://github.com/gioboa/jira-plugin/commit/9164ce6566073517f55914c8d26580fe5cdee0f9) I add some code for OAuth code.
@kahyoung I need your help to verify if like this can work. 👍

**Comment by gioboa** [comment]
Now master branch use jira-connection lib. [v. 0.7.0](https://github.com/gioboa/jira-plugin/releases/tag/0.7.0) <br>
@kahyoung  Did you try with OAuth Authentication?

**Comment by blueo** [comment]
FWIW I just tried logging in with a google account - and no joy. It looks as though i'd need to add consumer keys etc?

**Comment by gioboa** [comment]
@blueo Yes, you understand the problem. <br> I don't have the possibility to try with OAuth Authentication. In `src/http/api.ts` there is the connection method. <br> Can you help me to implement OAuth Authentication connection? <br> You can follow [CONTRIBUTING.md](https://github.com/gioboa/jira-plugin/blob/master/CONTRIBUTING.md) doc and create a PR. 👍  <br> Let me know. Thanks. 😄

**Comment by gioboa** [comment]
Waiting for the PR.

**Comment by NKjoep** [comment]
Hello, 

I came here for the same reason, I'd like to _connect_ to Jira with a user token. 

Reading the [jira-connect documentation](https://github.com/floralvikings/jira-connector), it looks like it's just not supported.

However, according on the [Atlassian documentation](https://confluence.atlassian.com/cloud/api-tokens-938839638.html), the user token can be used as a password for basic auth :) 

And the example is pretty straighforward and works indeed: 

```shell
curl -v https://company.atlassian.net --user your@email.com:token
```

Then I have question: why doesn't this work with `jira-connect` (and so with this beautiful vscode pluing)? What am I missing?

**Comment by gioboa** [comment]
Hi, so even if you put your email in user and the token inside the password the authentication went wrong?

**Comment by NKjoep** [comment]
Yes, it went wrong and I get the long log in the vscode extentension output panel.

**Comment by gioboa** [comment]
So if we insert in **user** the `email` and inside **password** the `token`, will it work correctly?

**Comment by NKjoep** [comment]
*Correct!*

It worked like this for me:

 0. go to https://id.atlassian.com/manage/api-tokens and create a token
 1. close all the vscode
 2. open one vscode instance
 3. setup the jira-plugin with: 
 3.a url: your base atlassian url (https please!)
 3.b username: your full email
 3.c passowrd: the token

**Comment by blueo** [comment]
so this worked for me too, thank you for the instructions!
