### ISSUE TITLE
feat: Setting to match git branch name with jira project id when they are different

### ISSUE THREAD

**Issue by magneticcore** [gioboa/jira-plugin#120]
The goal is to have a setting to match git branch name with jira project id when they are different to update git information as well, for example:
Jira project id: MYPROJ
git branch: feature/MYNEWPROJ

The setting can be a string which gives the matching: MYPROJ=MYNEWPROJ

So each time Jira plugin needs to use the Jira project id for git, it translates it to its matching value: MYPROJ-68 (Jira) => MYNEWPROJ-68 (Git)

**Comment by gioboa** [comment]
Yes, this feature has sense.
I will think how implement a simple setting for map the values.

**Comment by magneticcore** [comment]
Github....no-issue-activity

**Comment by gioboa** [comment]
@magneticcore Are you still interested at this feature?

**Comment by magneticcore** [comment]
Yes, absolutely!

**Comment by gioboa** [comment]
I've built an alpha version to test this fix.
Please have a try and give me feedback. :+1:
If all it's ok I will release a new official version. :smile:

[jira-plugin-0.18.5-alpha1.zip](https://github.com/gioboa/jira-plugin/files/3866355/jira-plugin-0.18.5-alpha1.zip)

**Comment by magneticcore** [comment]
I will check this afternoon and tomorrow and I will give you a feedback. Before installing it, did you add a setting to do the mapping as described in my initial comment?

**Comment by gioboa** [comment]
Yes, I added a setting. You can find a description [here](https://github.com/gioboa/jira-plugin/blob/develop/README.md#settings) _Project Key Mapping_ 😄 👍

**Comment by gioboa** [comment]
Released in v 0.19.0
