### ISSUE TITLE
issue: Unable to verify the first certificate with VS Code 1.36

### ISSUE THREAD

**Issue by magneticcore** [gioboa/jira-plugin#121]
After VS Code updating to v1.36 from 1.35, Jira Plugin stopped to work, raising the error "Unable to verify the first certificate" (before updating, all was ok).

For a test, I tried to use the environment variable NODE_TLS_REJECT_UNAUTHRIZED=0, but without success, VS Code giving me another error.

Any idea?

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by magneticcore** [comment]
I put also your setting jira-plugin.strictSSL to false and http.proxyStrictSSL to false with http.proxy correctly given

**Comment by gioboa** [comment]
Hi @magneticcore , 
Did you try to set StrictSSL param?

**Comment by magneticcore** [comment]
In the output log of Jira-Plugin, there is only the error message "unable to verify first certificate"

**Comment by gioboa** [comment]
Have a look at [this issue](https://github.com/gioboa/jira-plugin/issues/1) maybe are related. 
I think you can solve the problem by using [this extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca)

**Comment by magneticcore** [comment]
After rolling back from version 0.18.1 to 0.17.0, Jira plugin is working again, I just needed to switch the setting jira-plugin.strictSSL to true, reload vscode, switch to false and reload vscode.

**Comment by gioboa** [comment]
So now you are using 0.17.0 version? Mmmm... maybe it's a dependency lib issue...

**Comment by magneticcore** [comment]
Yes, I'm using again 0.17.0 and it works, but only after doing the switch on/off of the setting jira-plugin.strictSSL.

**Comment by gioboa** [comment]
I checked the code of the dependency lib and seems ignore my strictSSL flag.
I will fix the plugin code and I will release a new minor version.
Thanks for your feedback 👍

**Comment by gioboa** [comment]
The new version [0.18.2](https://github.com/gioboa/jira-plugin/releases/tag/0.18.2) will solve this issue.
You must set strictSSL = 'false', restart VsCode and it will works as expected. 👍

**Comment by magneticcore** [comment]
Version 0.18.2: Work again perfectly, thank you for the correction and reactivity!
