### ISSUE TITLE
feat: Field for time estimation in the creation menu

### ISSUE THREAD

**Issue by jrpub** [gioboa/jira-plugin#124]
It seems the option to add the time estimation for an issue does not exist. 

In my Jira, this field is: "Original Estimate", described as "The original estimate of how much work is involved in resolving this issue."

It is frustrating to log time without being able to enter the estimated time :-)

I didn't find a workaround, except to set the estimate in Jira each time I create a new issue, which break the workflow offered by the plugin.

**Comment by gioboa** [comment]
Hi @jrpub ,
I think the field is not managed. I will work to implement the possibility to insert also this particular field. Next week I will work on this. Thanks for your feedback and if you have any other suggestions please open an issue/feature request.

**Comment by gioboa** [comment]
@jrpub 
I created an alpha package with this implementation. If you can test the functionality and all It's ok, I will publish the new release.

[jira-plugin-0.18.3-alpha1.zip](https://github.com/gioboa/jira-plugin/files/3503235/jira-plugin-0.18.3-alpha1.zip)

Thanks in advance for your help. :+1: :1st_place_medal:

**Comment by jrpub** [comment]
I tested. It works a bit, but not fully: I can enter an Original Estimate and a Remaining Estimate, but the entered values are different on the Jira side:

- I entered "7h" and "6h" respectively
- Both values are converted in Jira to: "1d 2h" and "1d 1h". 

This seems to be a conversion issue. 

In addition, I noticed that "Fix version" does not work (no value in Jira), but it was also the case with the 0.18.2 so this bug is independent. Let me know if you want I open a new issue for this one. 

Let me know if I can help!

**Comment by gioboa** [comment]
Yes open a new issue for fix version.
In Jira web application if you enter 7h and 6h there are some conversions?

**Comment by jrpub** [comment]
Ok, I checked, and everything is fine. It was on the Jira side, it converts automatically based on the configuration, notably the number of hours in a workday (which is configurable). 
In the help of these fields, I saw that:

```

**Comment by gioboa** [comment]
Great :+1: I will publish an official release next week with this feature. :smile: 
Thanks for your help :1st_place_medal:
