### ISSUE TITLE
feat: vscode confirm exit when counting time

### ISSUE THREAD

**Issue by gustavobcampos** [gioboa/jira-plugin#125]
**Is your feature request related to a problem? Please describe.**
Closing VSCode when working on an issue throws the time away.

**Describe the solution you'd like**
VSCode asks if you really want to close it with an ongoing timer.

**Describe alternatives you've considered**
When reopening VSCode the time is not lost, it is reloaded in some sort of cache
Closing VSCode automatically submits issue time

**Comment by gioboa** [comment]
Hi @gustavobcampos , there is a mechanism to retrieve the previous working time if you close VsCode before submit the worklog.
Did it works in you scenario?
I will check if there is the possibility to prevent VsCode for exit. :+1:

**Comment by gustavobcampos** [comment]
"if you close VsCode before submit the worklog, there is a mechanism to retrieve the previous working time."
I tested this and it did not work, when I reopened VSCode no working issue was set, is there a setting that I'm missing?

**Comment by gioboa** [comment]
No the plugin do it automatically.
If we implement the dialog before vscode close we can solve the problem without restore any previous pending working. We kill two birds with one stone.:+1:

**Comment by gioboa** [comment]
I studied VsCode code and all the events (onClose etc. etc.) unfortunately are private and the others dispose methods are call too late.
I tested my implementation for retrieve the last not stopped work issue and it works. 
The plugin every minute, if there is a current working issue started, it write in the private VsCode memory and then at startup resume it. [here the code](https://github.com/gioboa/jira-plugin/blob/91cba84d66376e0844d369299171aca661d41663/src/services/configuration.service.ts#L91) I decided to save every minute for performance reason.

**Comment by gustavobcampos** [comment]
I retested the feature that saves time on VSCode close, and it works sometimes, I decreased the time which the plugin saves the working issue, and it worked seemed to help a little, but still bugs sometimes.

I also asked a friend to test on his Notebook and it did not work too. I don't know if it's something related to our SO (we both have Ubuntu 18.04), but when we reopen VSCode the plugin loses track of the previously set project, and not only the issue time.

I would really appreciate if you could fix this, I'm a Product Owner and I am implement this plugin in my company, but I'm afraid that Devs forget to submit the issue before closing VSCode and losing this data.

Thank you very much, this extension is being very helpful for me!

**Comment by gioboa** [comment]
> the plugin loses track of the previously set project, and not only the issue time.
Working project is saved in setting.json file ( under .vscode folder ).
When you open a project / folder the plugin read the config from this file and use general settings as fallback. Saving working issue evrey 1 min maybe can be replace with other logics.

**Comment by gioboa** [comment]
Notice: this issue has been closed because it has been inactive for more than 7 days.
You may reopen this issue if it has been closed in error.
