### ISSUE TITLE
issue: Fix version field not working when creating an issue

### ISSUE THREAD

**Issue by jrpub** [gioboa/jira-plugin#126]
When creating an issue, filling the "fix version" does not work, the field remains empty on the Jira side. 

In Vscode, we see correctly the list of the versions, but selecting one and saving the issue leaves the "fix version" value blank on Jira.

**Comment by gioboa** [comment]
Thanks for the feedback. I will check the Jira API call for create a new issue.

**Comment by gioboa** [comment]
I've done a test and I created correctly a issue with a fix version.
I've done the test into my Jira cloud server.

**Comment by gioboa** [comment]
@jrpub Did you try again to create an issue with fix version field?

**Comment by gioboa** [comment]
@jrpub Do you have any news?

**Comment by gioboa** [comment]
Notice: this issue has been closed because it has been inactive for 7 days.
You may reopen this issue if it has been closed in error.
