### ISSUE TITLE
feat: merging Todo+ ideas to Jira plugin?

### ISSUE THREAD

**Issue by jrpub** [gioboa/jira-plugin#128]
Using both Jira-plugin, and Todo+, I find that both plugins are wonderful. 

**With Todo+:**
I like how it is fast to enter / toggle / change the status of an issue, as it is fully text based. Furthermore, I like the presentation (colors and icons). Currently, I use it for my "micro-tasks". 

**Jira-plugin:**
I like it because I can create a Jira issue without moving away from Vscode, and for the time tracking features, and because there is Jira behind. 

It would be extremely interesting to make a combo of the two. Being able to enter a Jira issue with one line, and to "move" (eg change the status) of each task just by copy pasting the line would be very great.
It would be a "textual version of Jira", where all issues can be managed by editing a todo file. It might be a feature I would be ready to pay for.

**Comment by gioboa** [comment]
Hi @jrpub
I never used Todo+, but I will download it and I will study it.
Simplify the user experience anyway is always good point to reach. :+1: 
Thanks for your feedback and ideas. :100:
