### ISSUE TITLE
Qustion about Oauth

### ISSUE THREAD

**Issue by lart2150** [gioboa/jira-plugin#129]
The description of this plugin talks about oauth support and issue #52 seems to indicate that oauth was added however https://id.atlassian.com/manage/api-tokens is api tokens not oauth.  Sadly api tokens only works for cloud.  oauth requires a handshake to generate a token so it's not like you can just grab a oauth token that's already generated for another application (like bitbucket, confluence, bamboo) and use it for this plugin.

**Comment by gioboa** [comment]
Hi @lart2150 ,
I don't understand the problem. Have you got an authentication problem?

**Comment by gioboa** [comment]
Notice: this issue has been closed because it has been inactive for more than 5 days.
You may reopen this issue if it has been closed in error.
