### ISSUE TITLE
unable to connect to intranet jira server

### ISSUE THREAD

**Issue by rupalidesai** [gioboa/jira-plugin#13]
Hi,

I have installed JIRA server in the network on a windows 7 machine.
I am trying to setup creditials using the URL as
"http://192.*.*.*:8080" and then my JIRA username and password where * is the local IP of the machine.

I am receiveing  "Failed to connect to JIRA" error?
Am I missing anything?
Please help.

Thanks
Rupali

**Comment by gioboa** [comment]
Hi, your Jira server respond on port 8080? If yes, I think there are some fixes to do for use that port.
A fast solution can be map in the "etc/host" of your machine the Ip https://192.x.x.x:8080 to https://xxxxx.com and setup the credential in the plugin. :smile:

**Comment by gioboa** [comment]
@rupalidesai with jira-connection branch works?

**Comment by gioboa** [comment]
@rupalidesai In the v. 0.7.0 the plugin parse the baseUrl to detect protocol, url and port. <br> 
e.g. `http://192.*.*.*:8080` <br>
Now you can use the plugin with your local Jira. 😄 👍
