### ISSUE TITLE
Use JIRA function membersOf() for assignees list

### ISSUE THREAD

**Issue by gchr** [gioboa/jira-plugin#130]
**Describe the issue**
Trying to use the membersOf() function in jira-plugin.workingIssueAssignees setting

**To Reproduce**
1. Set in settings:
`"jira-plugin.workingIssueAssignees": "membersOf(data-feed-developers)", `
where 'data-feed-developers' is a valid group in Jira server
1. Close VSCode
1. Start VSCode (to make sure the 'working Issues' are not cached)
1. Click on 'Set working issue'

A notification shows up :
No STATUS: 'To Do','IN PROGRESS', ASSIGNEES: 'membersOf(data-feed-developers)' issues found in ETSSWEB project

**Expected behavior**
The list of issues, as if jql :
`status = "In progress" AND project = ETSSWEB AND assignee in (membersOf(data-feed-developers) )
`
was used

**Screenshots**
N/A

**Desktop (please complete the following information):**
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

**Log**
Nothing is shown in the log

**Comment by gioboa** [comment]
I will check the possibility to use membersOf function. :+1:

**Comment by gioboa** [comment]
I've build an alpha version to test this fix.
Please have a try and give me feedback. 👍 
If all it's ok I will release a new official version. 😄 

[jira-plugin-0.18.4-alpha.zip](https://github.com/gioboa/jira-plugin/files/3591196/jira-plugin-0.18.4-alpha.zip)

**Comment by gchr** [comment]
I've started using it today. It's working great! 

I also tried combining a name with membersOf, too, and everything seems ok.
"jira-plugin.workingIssueAssignees": "Dev.Name,membersOf(data-feed-developers)"

Great job!
Thank you!
