### ISSUE TITLE
bug: wrong git branch name detection when submodules are present

### ISSUE THREAD

**Issue by caleb15** [gioboa/jira-plugin#132]
**Is your feature request related to a problem? Please describe.**
Often I forget to set my working issue.

**Describe the solution you'd like**
Upon workspace open or branch switch the jira extension would automatically scan the branch name for possible jira tickets (maybe using a regex like `(\w+-\d+)`) and if it matched a in-progress issue id for the current project than that issue would be set to in progress. 

**Describe alternatives you've considered**
I slap myself every time I forget to set the working issue until I remember. I'd prefer not to go this route for obvious reasons.

**Comment by caleb15** [comment]
I tried to donate a couple euro to you but unfortunately it didn't work for some reason :( 

Maybe [github sponsors](https://github.com/sponsors) would work better?

**Comment by gioboa** [comment]
Hi thanks for your feedback.
The plugin already try to parse git branch name to change working issue.
At this line the code https://github.com/gioboa/jira-plugin/blob/d0894dfbe5ab42ef9924f2da1bb4dd15140b2596/src/services/git-integration.service.ts#L154
For git sponsor I will check how to add it  :+1: :smile:

**Comment by gioboa** [comment]
The regex catch branch named like this MYPRJ-123. Maybe we can improve the logic of matching. :+1: let me know :smile:

**Comment by caleb15** [comment]
Ah, I guess this is actually a bug then. When I switch to a branch that matches a in-progress issue nothing happens. For example, DEV-551 is in progress but when I switch to a branch called DEV-551 I still have "no working issue" and I don't see any error logs in the console.

Here's how it would be parsed according to your regex:

****
![image](https://user-images.githubusercontent.com/46505081/68049930-548d6e80-fca1-11e9-8430-b1750df2bc5f.png)

It looks like your regex is good so not sure why it's not working :thinking:

**Comment by caleb15** [comment]
my vscode info:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-32-generic snap
```

extension info: 
```
Name: Jira Plugin
Id: gioboa.jira-plugin
Description: Manage your on-premises/cloud Jira in vscode
Version: 0.18.4
Publisher: gioboa
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=gioboa.jira-plugin
```

**Comment by gioboa** [comment]
Do you see DEV-551 in your "valid" working issue list? The plugin check the regex and if is a valid working issue.

**Comment by gioboa** [comment]
The fastest way to understand the problem is hack the plugin code.
In this folder you have all installed extensions
%USERPROFILE%.vscode\extensions
If you open with text editor this file
%USERPROFILE%.vscode\extensions\gioboa.jira-plugin-xx.xx.xx\out\src\services\git-integration.service.ts
You can debug the code.
console.log are visibile in VsCode dev tool - Help > Toggle Developer Tools
parseTicket is a good method to start

**Comment by gioboa** [comment]
@caleb15 Did you find something?

**Comment by caleb15** [comment]
Yeah, I found the problem. I have a submodule in my repository, but the code only grabs the first item from `getGitRepositories`, which in my case happens to be the submodule. 

```javascript
const [repo] = yield this.getGitRepositories();
```

![image](https://user-images.githubusercontent.com/46505081/68914525-b7f0b500-0713-11ea-9bf5-9082695fc045.png)

The above picture is the result of `this.getGitRepositories()`. The first item with the longer path is a submodule of the second item.

**Comment by caleb15** [comment]
I also had to set the `gitIntegration` setting to true - the default is false.

**Comment by gioboa** [comment]
:+1: Great! So now works as expected? Can we improve the code in some aspects?

**Comment by caleb15** [comment]
It doesn't work as expected. When I am in a project with a submodule it doesn't automatically switch the ticket based on branch name for the reason explained in my comment above. :(

To fix it you would need to check the branch name of each repository returned by `getGitRepositories`instead of just the first one. Currently you cache the current branch name so you would also have to change the cache to work per-repository.

**Comment by gioboa** [comment]
I will fix it, please give me an example to use for testing. Thanks. :+1:

**Comment by caleb15** [comment]
Just add a submodule to your repository and delete it afterwards:

`git submodule add https://github.com/<user>/<repoName> <name>`

You can add any random repo as a submodule ^

`git submodule update --init --recursive`


https://github.blog/2016-02-01-working-with-submodules/

**Comment by gioboa** [comment]
I've built an alpha version to test this fix.
Please have a try and give me feedback. +1
If all it's ok I will release a new official version. smile

[jira-plugin-0.18.5-alpha1.zip](https://github.com/gioboa/jira-plugin/files/3866355/jira-plugin-0.18.5-alpha1.zip)

**Comment by caleb15** [comment]
Thanks! The jira extension recognizes main repo branches with a jira id now :) 

It doesn't recognize branches within a submodule though. Personally speaking I don't care about branches in my submodule but eventually you might get someone reporting an issue for that FYI.

**Comment by gioboa** [comment]
Yes, thanks for your feedback. The plugin take always the last repo in got repositories and the last is the main branch. :+1:
