### ISSUE TITLE
Project: NONE

### ISSUE THREAD

**Issue by hmendezm** [gioboa/jira-plugin#133]
**Describe the issue**
I entered the Jira URL and credentials and not an error. However when I click "Project: NONE" below in the bar. I get the msg 'Check logs in Jira Plugin terminal output'. How do I get the terminal out?

Best
H. Mendez

**Comment by gioboa** [comment]
Hi, here you will find the [output log](https://github.com/gioboa/jira-plugin/issues/34) :+1:

**Comment by hmendezm** [comment]
Thx
