### ISSUE TITLE
feat: add option to include projects #109

### ISSUE THREAD

**Issue by copdips** [gioboa/jira-plugin#135]
Hello,

As #109 is closed, I open this issue to address the same feature because in the current JIRA-PLUGIN version,  we can still only exclude but not includ.
Our JIRA is hosting 100+ projects, too difficult to exclude.

**Comment by gioboa** [comment]
Hi, I will implement the possibility to set only the projects you desire. If this config is present it will override all projects list.

**Comment by gioboa** [comment]
@copdips in v 0.19.0 I added projectsToShow setting. Here you can define only the projects to include.

**Comment by gioboa** [comment]
If you like it, please star the repo. Thanks.
