### ISSUE TITLE
feat: Subtask as working issue

### ISSUE THREAD

**Issue by micharaze** [gioboa/jira-plugin#139]
**Is your feature request related to a problem? Please describe.**
When I want to select a working Issue to log my working time it is not possible to select a Subtask. The Jira Plugin only lists Stories and Tasks from current sprint. 

**Describe the solution you'd like**
It would be helpful when it is possible to select also Subtasks as a working issue.

**Comment by gioboa** [comment]
Hi, I retrieve working issue by Jira jql.
Can you give me an example for retrieve sub-tasks? Thanks :+1:

**Comment by micharaze** [comment]
I am using in Jira a Scrum board. I am usually creating Sub-tasks in a story. When I am using the following JQL command in the Jira JQL search then I also get the Sub-tasks listed.

```
status = "In Progress"
```

I don't know how your plugin is searching for Issues in progress. With the following command I am able to find all Sub-tasks in progress only:
```
issuetype = Sub-task and status = "In Progress"
```

I hope this helps.

**Comment by gioboa** [comment]
The plugin search for project/status/assignee
[Here](https://github.com/gioboa/jira-plugin/blob/aca9e7d1d57e6446be3313321bdaf4681cc60fb8/src/services/select-values.service.ts#L134) the code. :smile_cat:

**Comment by micharaze** [comment]
Ah, know I see the problem. Created Sub-tasks were not automatically assigned to me so I was not able to see them. 

Thanks! 😃
