### ISSUE TITLE
Issues with the filter command

### ISSUE THREAD

**Issue by ShadowFM** [gioboa/jira-plugin#14]
Hello,
I tried to search for a closed issue but if I try it with "done" or status = done it isn't working.
How does the filters work?

**Comment by gioboa** [comment]
Hi,
the plugin under the hood create for you jql for Jira.
So you try to filter by "status"=done and "summary"=done and you didn't have any result?

**Comment by gioboa** [comment]
@ShadowFM  did you solve?

**Comment by ShadowFM** [comment]
Yes, this worked, thanks :)

**Comment by gioboa** [comment]
:+1:
