### ISSUE TITLE
feat: Start/Pause button for Time tracking

### ISSUE THREAD

**Issue by micharaze** [gioboa/jira-plugin#140]
**Is your feature request related to a problem? Please describe.**
I often want to pause the time tracker when ich want to make a short break or else. The current process needs too many steps for just stoping the time, saving the log and then starting it again few minutes later. 

**Describe the solution you'd like**
What about an additional button for pause the time tracker on click and continue after a second click (⏸/▶️).

**Comment by gioboa** [comment]
I will implement it :muscle:

**Comment by gioboa** [comment]
I've built an alpha version to test this feature.
I've done start/stop button because pause icon has different color. :disappointed: 
Please have a try and give me feedback. :+1: 
If all it's ok, I will release a new official version. :smile: 

[jira-plugin-0.19.1.zip](https://github.com/gioboa/jira-plugin/files/4272006/jira-plugin-0.19.1.zip)

**Comment by micharaze** [comment]
Seems to working well. How about putting the clock together with the start/stop button in one field and the issue selecting in another. Currently the clock is together with the issue field and the start stop is alone. 

Currently:
Working Issue: IssueID123⌚00:23:54  |  ⏹ 

My suggestion:
Working Issue: IssueID123  | ⌚00:23:54 ⏹ 

So the functionalities are better separated. I hope this was clear enough described.

**Comment by gioboa** [comment]
Sure, great catch :+1:

**Comment by gioboa** [comment]
Here you can try an alpha version
[jira-plugin-0.19.1-alpha1.zip](https://github.com/gioboa/jira-plugin/files/4284005/jira-plugin-0.19.1-alpha1.zip)

**Comment by micharaze** [comment]
Looks good! Thanks for that.
