### ISSUE TITLE
I dont know how to set key mapping

### ISSUE THREAD

**Issue by SchmidtDawid** [gioboa/jira-plugin#141]
If my task in jira look like that: "APINT-3456 - bla bla bla" and i want to sync it with branches named feature/#3456 how my key should looks like?

And one question: Is it possible to create branches named by the same rule?

**Comment by gioboa** [comment]
Hi @SchmidtDawid,
the plugin use this RegExp -> "branchName".match(/([A-Za-z0-9]+)-(\d+)/)
You can also define your own mapping:
config: Project Key Mapping in [settings](https://github.com/gioboa/jira-plugin#settings)

_- Is it possible to create branches named by the same rule?_
Unfortunatly VsCode git integration doesn't allow you to define a default branch name

**Comment by SchmidtDawid** [comment]
Yes, but i don't know how to define my mapping. Should i pass 2 reqexes? or is there any variable to use? i don't understand this example CUSTOMKEY=JIRAKEY.

**Comment by gioboa** [comment]
Maybe some code explain better than words 😄 
[Here](https://github.com/gioboa/jira-plugin/blob/aca9e7d1d57e6446be3313321bdaf4681cc60fb8/src/services/git-integration.service.ts#L158) you have the code.
mapProjectKeyIfNeeed is the method that use this mapping configuration.

**Comment by SchmidtDawid** [comment]
Oh ok i get it now ;). Thanks!

**Comment by gioboa** [comment]
@SchmidtDawid Did you solve you issue? Can we close it?

**Comment by gioboa** [comment]
@SchmidtDawid Did you solve you issue? Can we close it?

**Comment by SchmidtDawid** [comment]
Yes :)
