### ISSUE TITLE
feat: Disable warning "Working project isn't set"

### ISSUE THREAD

**Issue by tfbroner** [gioboa/jira-plugin#142]
At the moment, when VSCode starts, or workspace folder changes, or if I open single file for editing, the plugin will SHOUT OUT LOUD "Working project isn't set", which is quite annoying to be honest. Can we have a setting to disable this please ?
![2020-03-03_10h43_24](https://user-images.githubusercontent.com/38210067/75768208-d1a61e80-5d3b-11ea-91e6-72446adffef9.png)

**Comment by gioboa** [comment]
Ok, I will check. :+1:

**Comment by tfbroner** [comment]
Thanks, I had quick look at the code, and while it would be trivial to add option to not show the warning, I don't think it's the right solution. I found out that the connection to the Jira server is being made whenever the plugin is activated, which means everytime the VSCode starts. 
Wouldn't it be better to do that on the explorer tab activation instead, or at least to make it optional?

**Comment by gioboa** [comment]
I can remove the message. I thought that it's a normal workflow when you open new project. What do you think?

**Comment by gioboa** [comment]
Here you can try an alpha version.
Please give me feedback. :+1: 
If all it's ok, I will release a new official version. :smile: 
[jira-plugin-0.19.1-alpha2.zip](https://github.com/gioboa/jira-plugin/files/4284021/jira-plugin-0.19.1-alpha2.zip)
