### ISSUE TITLE
issue: Can't set working project

### ISSUE THREAD

**Issue by ns-cweber** [gioboa/jira-plugin#144]
**Describe the issue**
Can't set working project 

**To Reproduce**

1. Install plugin
2. Setup credentials
3. Click the "Project: NONE" icon in the bottom left"
4. Type project into text entry at the top and press enter
5. Observe that nothing happens; text entry remains as though it didn't register the selection

My guess is that there is some issue connecting, but there is no error or output that indicates an issue. When the text entry appears, there is no list of projects below the entry to choose from like there is in the example images.

**Expected behavior**
I can select a project

**Screenshots**

**Desktop (please complete the following information):**

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Log**
```
Wrong configuration
Working project not correct. Select working project in the status bar.
```

**Comment by gioboa** [comment]
Hi, did you see any project in the list (step 3)?

**Comment by ns-cweber** [comment]
Nope, no project was listed. I should note that I'm connecting to an on-prem instance; however, the official jira plugin connects fine.

**Comment by gioboa** [comment]
The error was thrown [here](https://github.com/gioboa/jira-plugin/blob/1cc9882a397b68556c37a79abcc1a89fc46e7eb2/src/services/http.service.ts#L41) Try to reconfigure the settings please. :+1: 
Pay attention at your password or your token password. Thanks
