### ISSUE TITLE
Unable to set up project after logging in

### ISSUE THREAD

**Issue by MatrixArchitect** [gioboa/jira-plugin#149]
Hello,

After logging in to Jira from VS Code using Jira Plugin, when I click on the Project icon in the status bar, I get the following error in my Jira Plugin terminal output (the url pointing to confluence ends up in a 404):
{"statusCode":401,"body":"Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html\n","headers":{"server":"AtlassianProxy/1.15.8.1","content-type":"text/plain","strict-transport-security":"max-age=315360000; includeSubDomains; preload","date":"Wed, 01 Jul 2020 16:40:32 GMT","atl-traceid":"26f33971b7ae68ae","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","x-content-type-options":"nosniff","connection":"close","expect-ct":"report-uri=\"https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy\", enforce, max-age=86400"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"removed.atlassian.net","port":443,"hostname":"removed.atlassian.net","hash":null,"search":null,"query":null,"pathname":"/rest/api/2/status","path":"/rest/api/2/status","href":"https://removed.atlassian.net/rest/api/2/status"},"method":"GET","headers":{"authorization":"Basic YWJkdWwueW91c3VmemFpQG5lbGxzb25sbGMuY29tOkIhc20hfHxAaDc4NiE=","accept":"application/json"}}}

**Comment by gioboa** [comment]
Hi @MatrixArchitect , 
It's a well known log...
You can have a look at #148 issue.
You can use your personal token instead password :+1: 
If you like the project, please give it a :star: :smile:

**Comment by MatrixArchitect** [comment]
Thanks! Will do once I come up to speed on it on the plugin.

**Comment by gioboa** [comment]
Can I close this issue?
Did you solve the problem? 😉

**Comment by MatrixArchitect** [comment]
That seems to have solved this problem. Please go ahead and close it. Thanks for being prompt. :)

**Comment by MatrixArchitect** [comment]
My 2c: add this known issue to an FAQ?

**Comment by gioboa** [comment]
I mentioned this feature in the [docs](https://github.com/gioboa/jira-plugin#setup), maybe it is not visible enough :+1:

**Comment by MatrixArchitect** [comment]
I saw it, but it didn't register what it entailed. Not sure if there are others out there like me. But if there are, I would phrase it something like this: 
password: the token (make sure this your authentication token, not password, more info [here #148](https://github.com/gioboa/jira-plugin/issues/148)

Something like that. Just my 2c.

I left you a review on the market place.
