### ISSUE TITLE
Functionality request [change working issue name]

### ISSUE THREAD

**Issue by 7417667** [gioboa/jira-plugin#15]
I would like to have a functionality which can change 'working issue' from 'In progress' to custom name, for instance: Development In Progress, Test in Progress etc.
Ideally I wish I could predefine the list of names in form of array and pick them whenever I like

**Comment by gioboa** [comment]
Hi @7417667,
it can be a good functionality.
I think config param is good place for this list.

**Comment by 7417667** [comment]
Thank you @gioboa , looking forward to see the results.

**Comment by gioboa** [comment]
implemented in [this](https://github.com/gioboa/jira-plugin/commit/6f0900bcfcbda48252296bd700ab1f0a3cecaae4) commit 👍 available in v 0.8.0
