### ISSUE TITLE
feat: support copy remote url with Right-click menu

### ISSUE THREAD

**Issue by heartacker** [gioboa/jira-plugin#151]
hi, that will be greet if we can copy the remote url from Right-click menu. thanks.

**Describe the solution you'd like**
add copy url there. 3q
![image](https://user-images.githubusercontent.com/1876302/88295175-a4303080-cd2f-11ea-8141-b2ef5c7b5ff5.png)

**Comment by gioboa** [comment]
Hi @heartacker, I will implement this feature.
The implementation is quite simple and can help many users. 👍

**Comment by heartacker** [comment]
> Hi @heartacker, I will implement this feature.
> The implementation is quite simple and can help many users. 👍

😄 .thanks haha

**Comment by gioboa** [comment]
Implemented in [v 0.21.0](https://github.com/gioboa/jira-plugin/releases/tag/0.21.0) :+1:
