### ISSUE TITLE
issue: JIRA:EXPLORER Add comment cause errorMessages "Can not deserialize instance of java.lang.String

### ISSUE THREAD

**Issue by ididitmyway** [gioboa/jira-plugin#154]
**Describe the issue**
I just installed the Extension 2020/10/14
I set Strict SSL to false.
I able to create Issues, To JQL Issues and more.
I can not add a Comment to a ticket

**To Reproduce**

1. Go to 'JIRA:EXPLORER'
2. Right Click on a 'ticket'
3. Click on 'Add comment' 
4. Type text 'this is a test'
5. See error in OUTPUT JIRA-PLUGIN
"errorMessages":["Can not deserialize instance of java.lang.String

**Expected behavior**
A comment to the Issue was been added

**Desktop (please complete the following information):**

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.49.3 (system setup)
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:57:01.595Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

[OK] [Copy]

I replaced some personal informations in log with <....>

**Log**

{"statusCode":400,"body":{"errorMessages":["Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: org.apache.catalina.connector.CoyoteInputStream@5d38f2ff; line: 1, column: 2] (through reference chain: com.atlassian.jira.issue.fields.rest.json.beans.CommentJsonBean[\"body\"])"]},"headers":{"date":"Wed, 14 Oct 2020 11:38:49 GMT","x-arequestid":"818x3860301x1","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","content-security-policy":"frame-ancestors 'self'","x-asen":"SEN-2973962","set-cookie":["JSESSIONID=<12345628E1CA7BF08249BD7489>;path=/;Secure;HttpOnly","atlassian.xsrf.token=<BEsG-8OasD-Cs2-IPs5|c9s4bdf7181asd71fbcccdccf31c184>|lin;path=/;Secure"],"x-seraph-loginreason":"OK","x-asessionid":"69xcgx","x-ausername":"<myuser>","cache-control":"no-cache, no-store, no-transform","content-type":"application/json;charset=UTF-8","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"<myjira.mywebside.com>","port":443,"hostname":"<myjira.mywebside.com>","hash":null,"search":null,"query":null,"pathname":"/rest/api/2/issue/ABC-12/comment","path":"/rest/api/2/issue/ABC-12/comment","href":"https://<myjira.mywebside.com>/rest/api/2/issue/ABC-12/comment"},"method":"POST","headers":{"authorization":"Basic <mybasichasvalueasdkljasldkjasdlj>==","accept":"application/json","content-type":"application/json","content-length":93}}}

**Comment by gioboa** [comment]
Hi, which was the message?
Was it a simple string?

**Comment by ididitmyway** [comment]
The message was "this is a test"

**Comment by gioboa** [comment]
So really simple 😄 I will check the code 👍

**Comment by gioboa** [comment]
I'm looking at this issue....

**Comment by gioboa** [comment]
[v 0.22.2](https://github.com/gioboa/jira-plugin/releases/tag/0.22.2) release solved the issue.
