### ISSUE TITLE
feat: Multiple Jira Profiles/Instances

### ISSUE THREAD

**Issue by danstreeter** [gioboa/jira-plugin#155]
**Describe the solution you'd like**
Context: _I currently work within an agency setup where we are working for multiple clients across multiple projects. Some of which already have their own Jira instances which we work within._

What is the potential to have the ability to 'switch' between configured Jira profiles/instances, and set up multiples that can be selected in a similar way to 'Setup Credentials' is used on initial setup, but instead of overriding it would be 'Setup Instance' and add to a collection/list/array of instances that a new option 'Switch Jira Instance' could then drive selection, thus then changing the rest of the extension feature-set to the new Jira instance.

_With the addition of this functionality, you would also need to be able to manage the setup instances however a 'Delete Instance' option would probably be MVP which you could then run through 'Setup Instance' again to replace instead of a full edit journey._

**Comment by danstreeter** [comment]
My current limited understanding of what I'd expect to be 'secret management' within VSCode (and/or extensions) is limited, so I have no idea where the current 'Credentials' that are setup are stored, and how to view them, even if within code - however if you can point me to some documentation that covers this, I could potentially start looking at it, my thought pattern for this at present is as follows:

_This is all presuming that the credentials that are being stored can be done so in JSON, or another structured form_

- Implement 'secret' storage as array based per instance, so many 'instances' can be stored in the same 'secret'
- Changing the 'Setup Credentials' command to push to 'secrets[0]'
- Adding 'Instance Name' to 'Setup Credentials' command to provide feedback to 'Select Jira Instance' later
- Addition of 'Select Jira Instance' command to pull names from the secret array
- Addition of 'Add Jira Instance' to mirror setup credentials and push to 'secrets[]' array
- (At this stage, 'Select Jira Instance' should grow in line with additions)
- Implement 'live' credential usage from selection via 'Select Jira Instance'

**Comment by gioboa** [comment]
Hi @danstreeter ,
[here](https://github.com/gioboa/jira-plugin/blob/268a627aa6b4668a1e49bce91958ef069f5a1e88/src/services/configuration.service.ts#L17) you can find the vscode api to get the workspace storage. In this class there are all the methods for modify this storage. You can check and also debug the method setPassword or getCredentials. A migration form old credential logic must be implemented. Anyway an array of credentials can be a solution.

**Comment by gioboa** [comment]
[here](https://code.visualstudio.com/api/references/vscode-api) the vscode docs. At the end the famous getConfiguration method.

**Comment by danstreeter** [comment]
Hey @gioboa - Thanks for that, I'll take a look later.

Does the logic I've mentioned above look like a viable option, if so I'll start poking and see what I come up with.

**Comment by gioboa** [comment]
Yep, I don't know if official Jira Plugin for VsCode allow you to store different credentials.
Have a look at it, maybe we can find some cool ideas.
