### ISSUE TITLE
feat: View multiple projects at once

### ISSUE THREAD

**Issue by Vaelek** [gioboa/jira-plugin#156]
I work with multiple projects constantly. I created a filter that gives me what I want to see in the explorer, but it is always filtered to the active project. Having an "active project" in my use case really does not have a purpose and in fact only gets in the way. It would be great to be able to select a predefined filter and have it show all of the items that filter produces on its own.

**Comment by gioboa** [comment]
I will check the possibility to introduce an array of working project.

**Comment by Vaelek** [comment]
After I posted this I found an old stale-closed issue on the same topic that you had some discussion about a while ago. I attempted to implement this myself but the repo as-is fails on npm compile. So I've been modifying the extension in-place and have successfully removed the project filtering and just have to force Closed statuses to sort to the end and it fits the bill for me currently at least.

**Comment by gioboa** [comment]
Ok, anyway this feature I think can be useful for other users so I will check a clean way to do it. 👍 
Thanks for your feedback.
