### ISSUE TITLE
feat: Multiple Active Projects

### ISSUE THREAD

**Issue by JP01** [gioboa/jira-plugin#158]
**Is your feature request related to a problem? Please describe.**
Our company uses multiple active JIRA projects based on certain types of work (support, dev etc).  

**Describe the solution you'd like**
To be able to simply apply a filter and not have to set an Active Project. It would support working across multiple projects and still having all the tickets I'm assigned to visible.

**Describe alternatives you've considered**
Switching projects is fine because there's only 3 projects. But it would be great to be able to see all assigned tickets in 1 pane without having to switch.

**Additional context**

**Comment by gioboa** [comment]
Hi, this feature was asked so many times.
Currently all the logic are based with only one active project.
Anyway I will check if there is the possibility to implement it.

**Comment by JP01** [comment]
Thanks so much for this quick response! I just found the plugin today and it's very useful for keeping me on track with jira work :) 
We don't have access to internet on our dev machines so the fact that this works over local network is a huge benefit! :)

**Comment by JP01** [comment]
Hey Just wondering if this one ever made it into develop branch? :) Thanks for all your work!

**Comment by gioboa** [comment]
No, I'm sorry. This feature is not in the develop branch.
Currently I am quite busy. Can be a good first issue for some contributors. :+1:
