### ISSUE TITLE
feat: Manually add time logged

### ISSUE THREAD

**Issue by JP01** [gioboa/jira-plugin#159]
**Is your feature request related to a problem? Please describe.**
When switching active task - the options are to post time logged with or without a comment or not to post. It would be great if there was an additional option to manually type the time logged in. 
Sometimes the real time I want to log isn't exactly the same as the timer says (eg if I'm working on a few things at once I sometimes forget to stop the timer)

**Describe the solution you'd like**
It would be great to have an additional option to manually type the time logged when switching task.

**Describe alternatives you've considered**
Manually updating the ticket with my estimated time logged - it's good but involves going to Jira etc :)

**Comment by gioboa** [comment]
This feature is not so difficult to implement.
I will add the functionality. 👍 
Thanks for your feedback. 😄

**Comment by gioboa** [comment]
In the new release you will able to change also the time spent. :+1: :rocket:
