### ISSUE TITLE
feat: Change status with comment

### ISSUE THREAD

**Issue by JP01** [gioboa/jira-plugin#160]
**Is your feature request related to a problem? Please describe.**
Some of our rules are setup in Jira to require a comment when changing the status of a ticket eg closing Starting etc.

**Describe the solution you'd like**
It would be good if the "Change issue status" menu option also provided a comment field! :)

**Describe alternatives you've considered**
The alternative is to just open the ticket and manually update status :)

**Comment by gioboa** [comment]
I will check it. Thanks for your feedback
