### ISSUE TITLE
Error Transitioning Issue, field required.

### ISSUE THREAD

**Issue by DevBacega** [gioboa/jira-plugin#166]
**Describe the issue**
Hello!   I'm starting to use the extension, but when I'm going to change the status of a task, the extent of the error telling you you need to fill in a field, but the extension does not show up.   If I'm going to change the status on the platform, Jira actually shows me a modal with the required fields, is there any way to get around that in the extension?   Thank you very much.

**To Reproduce**
Change the status of a task that has a mandatory field.

![image](https://user-images.githubusercontent.com/54642509/119399795-b2ccd880-bcaf-11eb-8d64-25de5dddca2a.png)

**Comment by gioboa** [comment]
Hi, do you have any error in the console?
Guide - > #34
