### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abcgroupuae** [gioboa/jira-plugin#168]
- Issue Type: `Performance`
- Extension Name: `jira-plugin`
- Extension Version: `0.22.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\User\AppData\Local\Temp\gioboa.jira-plugin-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by gioboa** [comment]
Hi, thanks for your feedback. I will check the code.
@abcgroupuae  Did you notice this problem in older versions?
