### ISSUE TITLE
When ID search fails, side panel shows LOADING...

### ISSUE THREAD

**Issue by elste** [gioboa/jira-plugin#17]
if I search for a non-existent ID (eg 999999), the error message appears correctly, but the side panel shows "LOADING...".

**Comment by gioboa** [comment]
Hi @elste, 
I found the bug.
Solved with this [commit](https://github.com/gioboa/jira-plugin/commit/662c196f1126826191e8ccd7f6ba6bad460ef7b5).
Thanks. 🥇 👍
