### ISSUE TITLE
issue: "Handler already set!" while setting up credentials

### ISSUE THREAD

**Issue by ceIia** [gioboa/jira-plugin#170]
Hi! Just installed `jira-plugin` on VSCode.

I'm currently encountering the following error: `Command 'Jira-plugin: Setup credentials' resulted in an error (Handler already set!)` while trying to setup the extension.

**To Reproduce**

1. Install jira-plugin
2. Hit cmd+maj+p
3. Select `Jira-plugin: Setup credentials`

**Expected behavior**
Connect the plugin to my Jira account.

**Screenshots**
![image](https://user-images.githubusercontent.com/25929147/130252417-869e24ae-8ff5-407d-8626-65fb18f8c05f.png)

**Desktop (please complete the following information):**
```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (2 wks ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0
```

**Log**
Please check the [output log](https://github.com/gioboa/jira-plugin/issues/34) and paste here any logs.
I'm not sure how to access the `jira-plugin` specific logs, however in the Extension Host logs, there doesn't seem to be anything wrong related to the extension.
![image](https://user-images.githubusercontent.com/25929147/130253176-b1b85ab8-ea6b-4e43-aac8-a618495b135d.png)

**Comment by gioboa** [comment]
Hi, is the Jira URL a http public URL?

**Comment by ceIia** [comment]
Hi! I can't get to the step where I enter the URL with this error, as it occurs right as I press enter on the command.

Actually, I've found that the error doesn't happen when my VSCode panel is closed at the start. So if I close it (Cmd+J), reload VSCode and retry to initialize jira-plugin, it'll work. I think this might be a VSC issue. Weird.

**Comment by gioboa** [comment]
😲 wow really strange. Maybe you found a strange glitch in VsCode 😅 I hope you will enjoy the plugin 👍

**Comment by ceIia** [comment]
Haha yeah! Really needed it to track my time on each Jira issue.
Very cool, thanks @gioboa!
