### ISSUE TITLE
issue: Cannot change assignee when user starting with JIRAUSERXXXX

### ISSUE THREAD

**Issue by jaysonsosweet** [gioboa/jira-plugin#172]
**Description**
When trying to change assignee, I get a list with some of the users starting with JIRAUSERXXXX.  
When I select one of them I end up with the error, see attached screenshot:

**To reproduce**:
Simply right-click on issue and change issue assignee,
then select a user with prefixed JIRAUSERXXXX

**Expected behavior**
Issue assignee should be changed.

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/16287233/165911560-765a10bb-3f06-4427-b14d-eda30ffd15f0.png)
Error:  
![Annotation 2022-04-29 103221](https://user-images.githubusercontent.com/16287233/165910852-4cb24217-72e9-41df-bba1-6188bbb0ad05.png)

**Comment by gioboa** [comment]
Hi @jaysonsosweet.
are they (JIRAUSERXXX) different from the other users?

**Comment by jaysonsosweet** [comment]
Hey @gioboa !
Hmm different ? Not reallly... I mean I don't think so.
Like different how ?

**Comment by gioboa** [comment]
I mean different permission or settings inside Jira configuration
