### ISSUE TITLE
issue: Not able to login to Jira Plugin from VS code

### ISSUE THREAD

**Issue by Sandesh1112** [gioboa/jira-plugin#174]
Hello,

I am successfully install Jira Plugin 0.22.2 on my VS Code 1.70.2.
But not able to authenticate Jira with username and token...
Getting below error
Checks logs in Jira plugin terminal and Jira plugin terminal gives below error.
"[exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource."

Please do the needful.

**Comment by gioboa** [comment]
I see _redhat.vscode-yaml_ inside the warning message, seems to be an error from another plugin.
Please have a look at these steps for the authentication --> [OAuth login](https://github.com/gioboa/jira-plugin/issues/52)
