### ISSUE TITLE
feat: creating sub-tasks from context menu

### ISSUE THREAD

**Issue by alexey-kov** [gioboa/jira-plugin#175]
**Is your feature request related to a problem? Please describe.**
I wasn't able to find a way to create a sub-task since there is no field for parent issue

**Describe the solution you'd like**
Proposed way: in the Explorer tab, a user can find an issue and right-click it. A context menu will appear. In the menu, there should be an option "Create sub-task" (only if it is not a sub-task that was clicked on). Clicking on the option should launch the create issue dialogue with the parent issue field already populated.

**Describe alternatives you've considered**
Adding the "parent issue" field of the dialogue to explicitly specify it. I consider it more cumbersome, and moreover, it will increase the chance of a user's mistake.

**Comment by gioboa** [comment]
I will check how to implement it

**Comment by gioboa** [comment]
I really want to work on this, but unfortunately I am super busy at the moment

**Comment by alexey-kov** [comment]
I know how it feels. No pressure. The plugin is already very nice!
