### ISSUE TITLE
feat: "Set as a Working issue" context menu action

### ISSUE THREAD

**Issue by alexey-kov** [gioboa/jira-plugin#176]
**Is your feature request related to a problem? Please describe.**
We have a very big board with a lot of tasks, so a query done when trying to set a working issue could take a lot of time.

**Describe the solution you'd like**
It would be a lot quicker if I could just right-click an issue in the explorer tab and have an option "Set as a working issue" in the context menu. This way we don't need to re-query the server.

**Comment by gioboa** [comment]
Do you think is necessary check if the issue is ready to be a valid working issue?

**Comment by mktsolutions** [comment]
@gioboa I was unaware that such a check exists, but if it does, it makes perfect sense to perform the check. This way, the approach stays unified.

**Comment by alexey-kov** [comment]
@gioboa I was unaware that such a check exists, but if it does, it makes perfect sense to perform the check. This way, the approach stays unified.

**Comment by gioboa** [comment]
I really want to work on this, but unfortunately I am super busy at the moment
