### ISSUE TITLE
feat: view issue information

### ISSUE THREAD

**Issue by alexey-kov** [gioboa/jira-plugin#177]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to view information on the issue, at least on the one I am working on atm. At least the standard fields of Summary, Description, DueDate

**Describe the solution you'd like**
Add a new tab alongside the Explorer tab. Display information about the current working issue in this tab.

**Describe alternatives you've considered**
Alternatively, add a "View Description" context-menu action for the Explorer tab.

**Comment by gioboa** [comment]
Could you send me a mock-up/screen about your idea?

**Comment by alexey-kov** [comment]
@gioboa I was thinking about something like this:
![JP mock-up](https://user-images.githubusercontent.com/9558215/191441338-20f4c316-7672-450f-a98c-9e1d9a39e205.png)
Let me know if I wasn't clear enough

**Comment by gioboa** [comment]
It's super clear. Thanks, I will think about this implementation 👍

**Comment by gioboa** [comment]
I really want to work on this, but unfortunately I am super busy at the moment
