### ISSUE TITLE
Feature Request - Allow user to specify custom jira workflow

### ISSUE THREAD

**Issue by cryptogrampus** [gioboa/jira-plugin#18]
I have a custom JIRA workflow defined for story tickets. None of the states are named "In Progress" so these tickets don't show up in the plugin. I'm only able to see an epic which follows the default workflow.

**Comment by gioboa** [comment]
Hi @cryptogrampus ,
in the VS Code Jira-plugin settings there is `workingIssueStatues` used for extract working issue list (e.g. In Progress, Development In Progress, Test in Progress). 
I think it can solve you problem.

**Comment by cryptogrampus** [comment]
works! thanks! Sorry I missed your responses
