### ISSUE TITLE
how to prevent automatically creating of `.vscode/settings.json` file?

### ISSUE THREAD

**Issue by thilllon** [gioboa/jira-plugin#181]
Everytime I make a new project with vscode, this plugin automatically created `.vscode/settings.json` file with `"jira-plugin.workingProject": ""`. I can't find how to avoid this behavior. 

Thanks for your great work! This extension helps me a lot when I am working with Jira.

**Comment by gioboa** [comment]
Thanks for your feedback. What alternatives do you consider for archiving configurations?

**Comment by thilllon** [comment]
I hope this extension doesn't do anything when I create a new project, rather than create a settings.json file as it does now.
But can't find the proper config for disabling it.
![image](https://user-images.githubusercontent.com/44559468/221426215-24c4e19d-514c-4cbc-ac8e-b098e9ad78af.png)

**Comment by gioboa** [comment]
Now the plugin creates `"jira-plugin.workingProject": ""`
I will check the codebase to remove this default setting

**Comment by gioboa** [comment]
Here I created the version 022.3-beta.0, let me know if it solves the issue
[jira-plugin-0.22.3-beta.0.vsix.zip](https://github.com/gioboa/jira-plugin/files/10875809/jira-plugin-0.22.3-beta.0.vsix.zip)

**Comment by thilllon** [comment]
It works. Thanks!
