### ISSUE TITLE
Editing a PR comment results in `[object Object]`

### ISSUE THREAD

**Issue by BMMevius** [gioboa/jira-plugin#183]
## Explanation
When saving an edited PR comment, the comment is removed and replaced by `[object Object]`.
This is also visible on bitbucket.
![image](https://user-images.githubusercontent.com/36536314/227499673-37ec2e68-375f-4cf1-ae98-10237d2d45ce.png)

## Steps to reproduce
1. Create a PR comment.
2. Save it
3. Edit it
4. Save it

## System
VSCode 1.76.2
Jira Extension 3.0.2

**Comment by gioboa** [comment]
You opened the issue in the wrong repo, we have different [version numbers](https://github.com/gioboa/jira-plugin/releases) and a different name too...
