### ISSUE TITLE
Show child issues when searching for parent id

### ISSUE THREAD

**Issue by ReasonableDeveloper** [gioboa/jira-plugin#20]
Hey, thank you for this great extension.

I was wondering if it would be possible to show all child issues when searching for a (parent) task based on its ID. This would solve a big problem for me as `My issues filtered by status` means that I need to change my status filter two times when I want to work on another task. 
Lets take a look at following scenario. Say I have `Issue 1`, `Issue 1.1` and `Issue 1.2`.
I want to work on `Issue 1.1` so I first search for issues that are assigned to me based on the `todo`  status. I change the status of `Issue 1.1` to `in progress`. Now I need to change my status filter to `in progress` and can start working on the issue. The same thing needs to be repeated when I work on `Issue 1.2`. 
In this case it would be a lot easier to just search for the parent ID (`Issue 1`) and have all child tasks in one place regardless of their status. 

Let me know what you think and if I should create a PR.

**Comment by gioboa** [comment]
Hi @ReasonableDeveloper,
Maybe a good way to manage this scenario is to visualize in the explorer list the parent task. Under the parent also all child if present. What do you think? Can improve your daily workflow?

**Comment by ReasonableDeveloper** [comment]
Yes, adding hierarchy to the task explorer would be great.

**Comment by gioboa** [comment]
Perfect. 👍  Would you like create this PR?

**Comment by gioboa** [comment]
Waiting for PR. 👍

**Comment by gioboa** [comment]
With [this commit](https://github.com/gioboa/jira-plugin/commit/2738e3e41055f246aee2d7e7e1b81db3b3dcb8c3) I've done the feature.
Available in the next minor release. 👍

**Comment by ReasonableDeveloper** [comment]
Hey, I just found this task on my todo list. I'm sorry that I didn't send a PR as promised.
I probably forgot to upload my settings and extensions via the settings-sync plugin and as a result haven't had the plugin installed since I changed my working station a few months ago. :scream:

Needless to say, I'm installing the extension anew. Thank you for fixing my issue! :heart:
