### ISSUE TITLE
Add "Copy to clipboard" button to status bar

### ISSUE THREAD

**Issue by vody** [gioboa/jira-plugin#21]
During Jira issue development I am usually need to have a fast access to Jira issue key to use it in commit message or code comments. It would be good to add a "Copy to Clipboard" action button after Working Issue one in a status bar. Action should put working Jira issue key in clipboard in one click. This would allow to use it in commit message, code comments or snippets as well.

**Comment by gioboa** [comment]
Waiting for VsCode core API.

**Comment by gioboa** [comment]
I'm implementing the feature "copy to clipboard". @vody do you think that more generic option in the issue menu can do the job?

**Comment by gioboa** [comment]
Add copy to clipboard with #40 PR. :+1:

**Comment by vody** [comment]
Thank you @gioboa for this command. My minor comments are:
- My scenario was more about using Jira Key so can be used in commits or snippets. This cases would not require a summery, just key. 
- I did try to use your new command with [Status Bar Extension](https://marketplace.visualstudio.com/items?itemName=anweber.statusbar-commands) to do a an action as I need it, but failed as it is allowed to be executed only from EXPLORER (I think it is due to an idea that user select one in explorer, but I was about a current issue (of course only if there is one selected)): 
![image](https://user-images.githubusercontent.com/1209989/51091663-6aa16f80-17f2-11e9-9f5a-90295dc0f769.png)
Settings: 
`
    "statusbar_command.commands": [
        {
            "text": "$(clippy)",
            "tooltip": "Copy Jira Key to Clipboard",
            "alignment": "left",
            "priority": 90,
            "command": "jira-plugin.copyJiraSummary"
        }
    ]
`

**Comment by gioboa** [comment]
Hi @vody ,
yes, the method has one parameter, if it's undefined return this error.
[Here](https://github.com/gioboa/jira-plugin/blob/618d3f7294c7fcd179338e5e23c398590765f86c/src/shared/utilities.ts#L74) the method. 
If you can't pass params, you must create a new command for copy current working issue key.
Could be nice add a setting for set which data has to be copy.  (key/summary/key+summary)

**Comment by gioboa** [comment]
Would you like create a pull request for this feature? :+1: :question:

**Comment by vody** [comment]
@gioboa, I would try (no promises as I am not good in ts)  👍 How to get a current work item reference?

**Comment by gioboa** [comment]
Don't worry about TS, it's easy and much cleaner then vanilla js. Working Item reference is in [this](https://github.com/gioboa/jira-plugin/blob/a415e87bb329efc1e89ed1743428311bbde7f225/src/state/state.ts#L43) object. :+1:

**Comment by gioboa** [comment]
Waiting for your PR.
