### ISSUE TITLE
custom workflow mapping

### ISSUE THREAD

**Issue by FedeDR** [gioboa/jira-plugin#23]
like "Working issues Statues" setting (that can specify the custom workflow statues as working statues)
I think is usefull add settings to map custom statues to "Open" list (I see the open statues has dedicated icon in explorer view) and "Done" list (according to jira statues category: To do, In progress, Done)

this settings can be also used to filter the issues

**Comment by gioboa** [comment]
Hi @FedeDR,
so your nice to have is define one or more status under "Open" and "Done"?
I think a better approach can be: add a setting to define custom statuses.
**e.g:** "My custom status" : "Open, In Progress, Done"
What do you think?

**Comment by FedeDR** [comment]
Hi @gioboa, thanks for the reply
if we define only the category "Open", "Done" (and the already defined "In progress")
maybe is better to approach the settings like the current "Working issue statues" setting

in a setting like:
`"my custom status": "Open, In progres, Done" (one of)`
we had to do a line for each status we define, so maybe we can be use this settings only in json visualizations?

istead a reverse settings:
`"Open issue statues": ["list", "of", "my", "custom", "statues"]
"Done issue statues": ["list", "of", "my", "custom", "statues"]`
can the used in both the settings visualization (new settings visualization and json visualization)

honestly I have not seen the plug-in source, so I don't know if this is a bad idea

**Comment by gioboa** [comment]
mmm, I don't understand very well your solution :confused:
Nowadays the plugin extract from Jira all the available statuses.
Maybe can be useful define one or more custom statuses for group multiple statuses.

**Comment by FedeDR** [comment]
ops, I'm sorri for unclear comment.
I'm agree with you. Is usefull define one or more custom statuses.
I suggest to follow the default status category of jira to grouping the statuses. 
![download](https://user-images.githubusercontent.com/7735194/47709025-b864fd80-dc2f-11e8-8bae-0e4cbc51f244.png)
Do you think we need more than the defaut ones?

**Comment by gioboa** [comment]
We can introduce a setting and set the default like Jira default status category.
`To Do Category` -> 'Open, Reopened'
`In Progress Category` -> 'In Progress'
`Done Category` -> 'Resolved, Closed'
Then in the explorer we will create a filter by category.
Later every user will modify the categories in the settings. 👍

**Comment by gioboa** [comment]
Waiting for PR. 👍
