### ISSUE TITLE
Feature: Create Jira Ticket

### ISSUE THREAD

**Issue by EisenbergEffect** [gioboa/jira-plugin#25]
It would be cool to be able to create new Jira tickets from the plugin directly.

**Comment by gioboa** [comment]
Hi @EisenbergEffect ,
the possibility to create Jira Ticket it's for sure a great feature.  👍
Choose the right creation workflow it's also really important. 
Have you got any idea for implement this workflow?

**Comment by EisenbergEffect** [comment]
@gioboa I don't have a lot of thoughts on it. I'm somewhat new to using Jira myself. However, I was in a meeting the other day with some coworkers and they were discussing how painful it was to create a ticket through Jira's site. So, I went poking around and found this plugin, which has a lot of great features, and I thought "if it just had some ability to create tickets, I think this would meet my coworker's needs". So, I thought I'd reach out.

**Comment by gioboa** [comment]
Yep, it can be a really great plus.
I schedule the implementation of this feature.
Any suggestions are welcome. 👍

**Comment by gioboa** [comment]
I thought a workflow like this. ( with many other fields )
![insert_ticket](https://user-images.githubusercontent.com/35845425/48301170-bc273880-e4e9-11e8-9a18-3092499cc651.gif)

**Comment by gioboa** [comment]
@MXM-7 I created a branch for this feature.
My last commit is a first easy implementation of a possible workflow.
Would you like to help me with this?

**Comment by gioboa** [comment]
I don't think so 😞 
You have to check VsCode API.

**Comment by MXM-7** [comment]
Do You think we can then improve the Jira-Pluggin section where the project and issue list is displayed (Adding button etc)

**Comment by gioboa** [comment]
Only if VsCode allow the functionality.
In the create_ticket branch I made a creation call (it works).
Now you can add an issue only with few info (type, summary, description), we can work for manage more fields.

**Comment by MXM-7** [comment]
I have cloned the branch and  will have a look and see what I can do . To be honest your work flow is functional and very usable. But would be glad if I can contribute to improve it or at least test it :)

**Comment by gioboa** [comment]
Now the functionality manage only 3 field.
If you want, you can try to add "priority" and "labels" field.
I will implement the possibility to open the created issue and manage the assignee field. 👍

**Comment by gioboa** [comment]
@MXM-7 did you do something?
do you need a help for manage priority and labels field? :smile:

**Comment by MXM-7** [comment]
@gioboa  Hello, I spent some time on that but mainly on learning more on vscode plugging creation. I found some existing pluggin with very advance UI (I guess it's possible to have something very user frendly)

**Comment by gioboa** [comment]
ok, for you it's ok if I will finish the functionality?
After, we can plan a graphic refactor 👍

**Comment by gioboa** [comment]
Functionality added in [v 0.10.0](https://github.com/gioboa/jira-plugin/releases/tag/0.10.0)
If you find some bug or something to improve please open a GitHub issue. 🥇

**Comment by EisenbergEffect** [comment]
Thanks for picking this up and working on it with such enthusiasm @gioboa ! I'm sharing this with the rest of the team today 😄

**Comment by gioboa** [comment]
I must manage all field types yet because for custom types retrieve the options is difficult. I hope can be a good base for you and your team.

**Comment by gioboa** [comment]
Functionality added in [v 0.10.0](https://github.com/gioboa/jira-plugin/releases/tag/0.10.0)
