### ISSUE TITLE
Input two workingIssueStatues in the VS Code Jira-plugin settings.

### ISSUE THREAD

**Issue by alexandremsouza1** [gioboa/jira-plugin#29]
Is it possible to put two types of status in the jira settings?
Ex: Testing and in progress

I restarting vs code but does not work.

Need help.

**Comment by gioboa** [comment]
@alexandremsouza1 yes, it is possible. This setting is for this purpose.
It must work.
Can you attach a screenshot of you setting? Thanks. :+1:

**Comment by alexandremsouza1** [comment]
![capturar](https://user-images.githubusercontent.com/38253342/48731828-1f6d4500-ec25-11e8-80fd-7857dfbc3fc0.PNG)

**Comment by gioboa** [comment]
The setting value it's correct. The plugin verify also that the status is valid and in the available status list.
If you set only `Testing` and the plugin search for `In progress` issue means that `Testing` is not valid status.
![schermata del 2018-11-19 21-45-44](https://user-images.githubusercontent.com/35845425/48734393-97e3fe00-ec45-11e8-8b29-39890f83f2c4.png)

**Comment by alexandremsouza1** [comment]
How to check valid status using the plugin?

**Comment by gioboa** [comment]
In the explorer, If you filter the issues for status, the plugin list you all the available statuses. :smile:

**Comment by alexandremsouza1** [comment]
Thank you man 👍

**Comment by gioboa** [comment]
Can I close the issue? It's all ok now?

**Comment by alexandremsouza1** [comment]
Yes

**Comment by alexandremsouza1** [comment]
sorry giboa, my function **jiraInstance.status.getAllStatuses()** retrun empty array.

I have a problem.

**Comment by gioboa** [comment]
Hi, could you open a different issue for that? I'm glad to help you.
