### ISSUE TITLE
command 'jira-plugin.setupCredentialsCommand' not found

### ISSUE THREAD

**Issue by jareis** [gioboa/jira-plugin#3]
After install... command 'jira-plugin.setupCredentialsCommand' not found

Also settings on local workspace, are does not working...

**Comment by gioboa** [comment]
Hi @jareis, 
after install, reload VS Code, from command palette Ctrl-Shift-P (Windows, Linux) or Cmd-Shift-P (OSX) type: _">Jira-plugin: Setup credentIals"_ 
Does it work?

**Comment by jareis** [comment]
Hi @gioboa,

I have done all that and more.

meanwhile i have installed on my home laptop and works fine... i suppose there is a problem with my work installation, maybe didn't installed correctly?

Anyway i suppose it's not a bug, strange behaviour... maybe tomorrow will work!

**Comment by jareis** [comment]
I will reopen this issue just to try to find why this happens:
- After a fresh install vscode ( antivirus disabled )
```
$ code --install-extension gioboa.jira-plugin
Found 'gioboa.jira-plugin' in the marketplace.
Installing...
Extension 'gioboa.jira-plugin' v0.5.0 was successfully installed!
```
I still have the same problem.

At this point i'm out of ideas... any suggestion?

**Comment by gioboa** [comment]
@jareis Yep, try to clean the extension cache folder of VS Code. In this folder VS Code store all the downloaded extensions.

**Comment by jareis** [comment]
So...

- I have deleted by hand all cache folders on Application Support
- I have deleted by hand the `~/.vscode/extensions/gioboa.jira-plugin` folder
- reinstalled...

And i still have the same issue

**Comment by jareis** [comment]
Used the vsxi file, installed, and the issue still exists

**Comment by gioboa** [comment]
Try like this:
- clone repo
- open jira-plugin folder
- launch debug
- another code window must appear
- look at the output in the terminal
![output](https://user-images.githubusercontent.com/35845425/42993764-81fc5392-8c0c-11e8-8ae9-cb14c1b963f0.png)

Thanks. 👍

**Comment by jareis** [comment]
So,
If i follow the steps that you gave:

 ```
Looking for parseable documents...
extension.js:28
Activating extension 'gioboa.jira-plugin' failed: Cannot find module 'isomorphic-fetch'.
extensionHostProcess.js:786
Activating extension `gioboa.jira-plugin` failed:  Cannot find module 'isomorphic-fetch'
```
After `npm install`, it works just fine

**Comment by jareis** [comment]
I have just compiled the vsxi file from the source, and runs perfectly.

The noticed that the version that i compiled has a different checksum that the one on the Microsoft Market Place.

MD5 (jira-plugin-0.5.0.vsix) = 4f399caeac8549a9bab72d625ca970be
MD5 (gioboa.jira-plugin-0.5.0.vsix) = e03a745ddc376fb23b89a9c8a991a2fb ﻿

Shouldn't both be the same?
﻿

**Comment by gioboa** [comment]
I don't know how VS Code create checksum, but I think that for every build is different. Now if you install the extension from marketplace it work?

**Comment by jareis** [comment]
Well install hover the marketplace still doesn't work...

And i have some problem connecting to JIRA on this network - it appears to be related with the network infrastructure, and not with the Plugin.

I will close the issue because:
1 - It couldn't be reproduced
2 - This issue may be related with the particular settings of the network that I'm in

thanks @gioboa
