### ISSUE TITLE
Cannot Comment

### ISSUE THREAD

**Issue by Kaffiend** [gioboa/jira-plugin#31]
**Describe the issue**
Cannot comment on issue, complains about missing assignee field.

**To Reproduce**
1. Have what jira calls a Next Gen project
2. pull all issues for project 
3. right click in explorer => add comment
4. enter text for the comment and submit

**Expected behavior**
Expected a comment to be created on the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/7826229/48812861-3fbf0180-ed02-11e8-9ba7-e638ac520d4f.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise

**Additional context**

**Comment by gioboa** [comment]
Do you remember if the comment had any mention like `[@]`?

**Comment by Kaffiend** [comment]
Confirmed fixed
