### ISSUE TITLE
Cannot Create Issue

### ISSUE THREAD

**Issue by Kaffiend** [gioboa/jira-plugin#32]
**Describe the issue**
Throws errors trying to create an issue. Also the scope of the command is not within the jira-plugin: scope of command filtering
**To Reproduce**
All the required fields were filled out, gif was just too big so i had to cut it.
![d37fa4c1-cdaa-435f-b32b-065c0ede84dd](https://user-images.githubusercontent.com/7826229/48813270-2919aa00-ed04-11e8-8f31-d524add45840.GIF)

**Expected behavior**
Expected to successfully create an issue

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Additional context**
The create issue command is not in the same scope as the rest of the jira-plugin: commands

**Output**
```json
Error: {"statusCode":400,"body":{"errorMessages":[],"errors":{"summary":"Field 'summary' cannot be set. It is not on the appropriate screen, or unknown.","description":"Field 'description' cannot be set. It is not on the appropriate screen, or unknown.","assignee":"Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown.","priority":"Field 'priority' cannot be set. It is not on the appropriate screen, or unknown."}},"headers":{"server":"Atlassian Proxy/1.13.6.2","cache-control":"no-cache, no-store, no-transform","content-type":"application/json;charset=UTF-8","strict-transport-security":"max-age=315360000; includeSubDomains; preload","date":"Wed, 21 Nov 2018 01:30:19 GMT","atl-traceid":"2ea86286b9fd3834","x-aaccountid":"557058%3Ac6de51c1-5643-4f86-b2ae-b00f948422a3","x-arequestid":"1d3a99b3-02ad-4e3b-84b1-2232b891b3d5","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","atl-tcs-time":"Cache Hit","x-ausername":"IanM","x-content-type-options":"nosniff","connection":"close","set-cookie":["atlassian.xsrf.token=B4D4-MOGQ-WPVC-7861_3f87b4ec58f6c535af575a86e5d87dfd554f4832_lin; Path=/; Secure"],"x-seraph-loginreason":"OK"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"devcssi.atlassian.net","port":443,"hostname":"devcssi.atlassian.net","hash":null,"search":null,"query":null,"pathname":"/rest/api/2/issue","path":"/rest/api/2/issue","href":"https://devcssi.atlassian.net/rest/api/2/issue"},"method":"POST","headers":{"authorization":"Basic aWFubUBjb21wbGV0ZXN5c3RlbXN1cHBvcnQuY29tOkNvZmZlZW5Db3BlMSMk","accept":"application/json","content-type":"application/json","content-length":245}}}
```

**Comment by gioboa** [comment]
Hi @Kaffiend ,
you should verify* the create screen that matches your issue type and project and make sure that the fields are present and available for completion.

* by creating an issue in the UI - do you get a screen with those fields on it? Make sure you use the same user, project and issue type you are using in Jira plugin.

**Comment by Kaffiend** [comment]
![image](https://user-images.githubusercontent.com/7826229/48844804-e938de00-ed68-11e8-88a7-b5e87ff0f6c7.png)

@gioboa here is the issue screen, like mentioned before this is what they call the next-gen jira and i'm not sure if has a different api that you consume, I imagine it is versioned endpoints so there should be a way to detect it if there is a difference.

When entering an issue i only have to fill in the one (what needs done) field and update the rest after the issue is created.

**Comment by Kaffiend** [comment]
@gioboa how are you depicting what fields are required to create an issue? Are you querying the project for issue context and their required fields?
Check [here](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#getting-metadata-for-creating-issues-examples) for discovering issue field schema, according to the `Discovering issue field data` section.

**Comment by gioboa** [comment]
Thanks, with your help I found the way to recognize mandatory fields.
Now I'm working to fix the code. 💯

**Comment by Kaffiend** [comment]
@gioboa Just an FYI i recreated my project using the original scrum and project type instead of next gen and it works as long as i dont have any mandatory fields. So this fix you're working on 'should' take care of both 😄

**Comment by gioboa** [comment]
So in this particular case `"customfield_10100":"Customer is required."` there is a custom field required.
Mmm, seems to be really hard manage all the possibilities.

**Comment by Kaffiend** [comment]
@gioboa you would need a way to dynamically build the menu options from the required fields, since jira allows custom fields and the ability to make them required or optional the plug-in will have to support them. From what i saw of the example response there isn't a field name other than `customfield_****, so if you built the create issue menu from the response metadata users wouldnt know what customfield_**** actually is..

Perhaps a config file dictionary to track the field names? you can get them from jira when setting them up..but its not ideal, just the only thing i can think of to build the menu in such a way.

I'm off the clock now so i can pull down the project and see if i can figure out anything that can help. I've used jira for several years now and i use it daily, this plugin, now that i have a taste of it is paramount to me :)
