### ISSUE TITLE
Issues filtered by status dont work

### ISSUE THREAD

**Issue by alexandremsouza1** [gioboa/jira-plugin#33]
The filter is empty!

![tela](https://user-images.githubusercontent.com/38253342/48844602-80aa2b00-ed81-11e8-9434-9c95a0fc0731.gif)

My language is in Portuguese, I believe this is a problem. 

Debugging I noticed that the function  **jiraInstance.status.getAllStatuses()**   returned nothing

I also noticed that even changing the default values (In progress) ​​of the settings, nothing happened

**Comment by gioboa** [comment]
The default 'In progress' status is for working issues search.
It's a strange situation, the plugin ask to Jira all the available statuses with this function `jiraInstance.status.getAllStatuses()`. This array must be populated.
Do you find any errors in the terminal output log?

**Comment by alexandremsouza1** [comment]
only this

![capturar](https://user-images.githubusercontent.com/38253342/48854291-af7fcb80-ed98-11e8-9aee-9c9c9a1a80aa.PNG)

**Comment by gioboa** [comment]
@alexandremsouza1 Hi,
in the v 0.10.4 I added a [new setting](https://github.com/gioboa/jira-plugin/blob/68a464bdef865110f428b32ccd1c72003d38abd0/package.json#L95) to solve this kind of problem.
It's a workaround for your issue.
Let me know. Thanks. 👍

**Comment by alexandremsouza1** [comment]
hi @gioboa  this version dont work. 
the error still persists.

if I try to change the issue status using the **change issue status**   they are displayed and when I try to view using the **Issue filtered by status** dont work.

**Comment by alexandremsouza1** [comment]
@gioboa 
 I used the new functionality and it worked but I can not point hours. Only with status "In Progress".

![teste](https://user-images.githubusercontent.com/38253342/48899051-9a0caf00-ee35-11e8-8ce2-6b0be1347f61.gif)

**Comment by gioboa** [comment]
@alexandremsouza1  You have to set also `workingIssueStatues`. 👍

**Comment by alexandremsouza1** [comment]
After reboot it worked!!!!

Very Very thank you.
