### ISSUE TITLE
Custom Required Fields

### ISSUE THREAD

**Issue by Kaffiend** [gioboa/jira-plugin#38]
**Is your feature request related to a problem? Please describe.**
Custom Required Fields are not populated in the create issue command.

**Describe the solution you'd like**
Query the [api](https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest&utm_medium=302#api-api-3-field-get) for the fields to build a dynamic menu including required custom fields when creating an issue

**Describe alternatives you've considered**
Manually configured custom fields to include in command menu.

**Comment by Kaffiend** [comment]
The above linked api call is from version 3 (beta) of the api and seems to be the animal we are looking for 😸 just looking at the example response it can be used to build the create issue menu from the response, including custom fields

`GET /rest/api/3/field`
```
[
  {
    "id": "description",
    "name": "Description",
    "custom": false,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "description"
    ],
    "schema": {
      "type": "string",
      "system": "description"
    }
  },
  {
    "id": "summary",
    "key": "summary",
    "name": "Summary",
    "custom": false,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "summary"
    ],
    "schema": {
      "type": "string",
      "system": "summary"
    }
  }
]
```

**Comment by gioboa** [comment]
@Kaffiend you are right. 👍
We can change the workflow.
1. First of first we choose the _issue type_.
1. With _issue type_ we can retrive all the fields.
1. Then for each field we need "display_name" and possible values.
@Kaffiend do you know how many types there are for "schema"? { "type": "`option`/`string`" ... }
We need also a Jira API for extract all the values for each field
1. Now we have all the information for create a Jira ticket 😸 
I hope Jira API help us.

Here one custom field straight from Jira response:
`createMetaData ... expand: 'projects.issuetypes.fields'`

{
hasDefaultValue:false
name:"Epic Link" <--- **it can be the "display_name"**
required:false
schema:Object {type: "any", custom: "com.pyxis.greenhopper.jira:gh-epic-link", customId: 10000}
custom:"com.pyxis.greenhopper.jira:gh-epic-link"
customId:10000
type:"any"
}

**Comment by Kaffiend** [comment]
Based on the schema of the custom field we then might have additional calls to get that fields options like a select (dropdown field), date we can just handle that on our own with validation, i'm trying to find the api call to get the options of configured select field.

**Comment by gioboa** [comment]
In the createMetaData response there is also the availableValues and for some field there is the uri for retrieve all the values. I'm working for create a configurable code. I've almost done then if you want you can have a look into the code.

**Comment by Kaffiend** [comment]
ok, ill give it a try this evening and let you know 😄

**Comment by Kaffiend** [comment]
ok, ill give it a try this evening and let you know 😄

**Comment by gioboa** [comment]
@Kaffiend Do you have some feedback?
If you don't have any feedback, we can close this issue. 👍 😄

**Comment by Kaffiend** [comment]
Apologies been a tad busy of late.
