### ISSUE TITLE
Switch to other Issue without logging the worktime

### ISSUE THREAD

**Issue by Sigggi** [gioboa/jira-plugin#39]
Right now I have to log the time I've spend on one issue if I want to switch to another issue or no issue. Sometimes I select an issue and decide that it would be better to work on another issue first. So I have to log that one or two minutes, and then delete the time logged in the issue.

If I change the issue, it should not be mandatory to log the time I spend on the current issue.

**Comment by gioboa** [comment]
Hi @Sigggi ,
I will check the current workflow because my idea it was to ask every time at user if create a worklog or not.

**Comment by Sigggi** [comment]
But if I answer no, the timer stops, and the issue does not change, only if
I click yes, or yes with comment, then the issue changes.

Am Do., 29. Nov. 2018 um 10:29 Uhr schrieb Giorgio Boa <
notifications@github.com>:

**Comment by Sigggi** [comment]
This bug is fixed in 0.10.6
