### ISSUE TITLE
Filter by JQL Custom Filter

### ISSUE THREAD

**Issue by yrwol** [gioboa/jira-plugin#41]
Hi, 

I would like the ability to provide a custom filter using JQL to display tickets.

Example: https://marketplace.visualstudio.com/items?itemName=crhistianr.jira-issues 

Thanks!

**Comment by gioboa** [comment]
Hi @yrwol ,
nice feature. I will implement it in the next release. 👍

**Comment by gioboa** [comment]
@yrwol The second idea for me it's much better.
I can't change the menu at runtime so I will implement a generic "custom filters" option and then the user will choose the custom filter from a list. What do you think?

**Comment by yrwol** [comment]
@gioboa that sounds perfect!

**Comment by gioboa** [comment]
I added the feature in [v. 0.11.0](https://github.com/gioboa/jira-plugin/releases/tag/0.11.0)
