### ISSUE TITLE
Comment Currently Working Jira Issue

### ISSUE THREAD

**Issue by yrwol** [gioboa/jira-plugin#42]
Hi,

I would like the ability to insert a comment that is the JIRA Issue ticket. It would be nice to be a short cut - the default short cut for comment is CTRL + /

i.e.

// JIRA-123

Thanks!

**Comment by gioboa** [comment]
@yrwol I don't understand the feature. Can you explain the workflow please. 😕

**Comment by gioboa** [comment]
Now I understand the feature.
I will check how implement it in the next release.

**Comment by gioboa** [comment]
I added the feature in [v. 0.11.0](https://github.com/gioboa/jira-plugin/releases/tag/0.11.0)

_In next releases I will implement this:_
When inserting - there are options a user might want...
1. Insert Above
2. Insert Below
3. Insert In-line
