### ISSUE TITLE
Unable to select assignee during create issue when list is too long

### ISSUE THREAD

**Issue by sethbacon** [gioboa/jira-plugin#45]
**Describe the issue**
Unable to create issue. Our list of jira users is quite long (hundreds of users) and I only get a single page of potential assignees (basically some of the a's) Typing my name does not find it in the list.

**To Reproduce**
1. Go to Command Palette
2. Type Jira
3. Select Insert Jira issue
4. Assignee is one of the *Required fields
5. Potential list appears to stop at @ 50 names.

**Expected behavior**
The full list of potential jira users should be returned and typing my name should return the correct assignee OR the ability to page through the list.

**Screenshots**
Attached.
![list](https://user-images.githubusercontent.com/14307877/50169729-65144080-02ab-11e9-8c66-6c591fcae1dd.PNG)
![typing](https://user-images.githubusercontent.com/14307877/50169742-6b0a2180-02ab-11e9-9531-5dde9fd1c8d6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 71

**Comment by gioboa** [comment]
Hi, you are right. In this [line](https://github.com/gioboa/jira-plugin/blob/ad759c5e83519251f0614458665b2b4dfea878d9/src/commands/create-issue.ts#L132) I limited the result to 50 rows and I don't remember why.
I will fix it soon, sorry... It's a big fault.

**Comment by sethbacon** [comment]
No problem, thanks for the quick response.

**Comment by gioboa** [comment]
@sethbacon solved with [v 0.11.1](https://github.com/gioboa/jira-plugin/releases/tag/0.11.1).
Please give me your feedback. Thanks. 👍

**Comment by sethbacon** [comment]
@gioboa Working great now!!! Thanks for your quick turnaround.

**Comment by SlawekJarosz** [comment]
@gioboa related to the above...  Our JIRA user list is well over 1000 so some users cannot be assigned to an issue.  Would it be possible to add a search function for a user in case the user name is outside of the 1000 preloaded ones?

**Comment by gioboa** [comment]
Hi @SlawekJarosz ,
I've defined 1000 because it's a Jira limitation for a jql.
As you say, the alternative it's create some search function.
Have you got a search field in your Jira web application?

**Comment by SlawekJarosz** [comment]
Hi @gioboa, thank you!

**Comment by SlawekJarosz** [comment]
Hi, BTW, I tested it and it works great.  Thanks for the quick update!

**Comment by gioboa** [comment]
Thanks for your feedback. It was a pleasure! :smile: :+1:
