### ISSUE TITLE
issue: Unable to create issues

### ISSUE THREAD

**Issue by LarBearrr** [gioboa/jira-plugin#46]
**Describe the issue**
After selecing a project, and trying to create a new issue from the Jira menu, the issue is not created and the Create issue menu repeatedly flashes.

**To Reproduce**
1. select the desired project from the status bar in VS Code
2. Open the Jira menu by clicking on the Jira icon on the left
3. Click the + to 'Create issue'
3. Select the issue type from the dropdown list
4. Notice and fill in the required fields by the starred items (e.g. Summary) by clicking on the item/field.
5. Click 'Insert issue' and notice the insert issue menu flashes and does not go away, or create the issue.

**Expected behavior**
After following the steps to create an issue, clicking 'Insert issue' from the create issue dropdown should close the dropdown and create an issue in the selected project.

**Screenshots**
![image](https://user-images.githubusercontent.com/28734844/50297404-58762080-0442-11e9-934f-8a60b4b8d875.png)

![image](https://user-images.githubusercontent.com/28734844/50297454-73e12b80-0442-11e9-81a7-01c847e7c37a.png)

![image](https://user-images.githubusercontent.com/28734844/50297736-1c8f8b00-0443-11e9-87b4-0db75cfb93e7.png)

![image](https://user-images.githubusercontent.com/28734844/50297686-02ee4380-0443-11e9-88b9-c2cac72a56f0.png)

![image](https://user-images.githubusercontent.com/28734844/50297788-3d57e080-0443-11e9-88d7-c28d1e0f74ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.16299

**Additional context**

**Comment by gioboa** [comment]
Hi @LarBearrr , 
do you have any other required fileds for task type?
Do you have any errors in the [output log](https://github.com/gioboa/jira-plugin/issues/34)?

**Comment by LarBearrr** [comment]
Thank you for the quick reply. 
1. The only other required field I see when I create an issue in Jira is the Reporter field:
![image](https://user-images.githubusercontent.com/28734844/50300235-7430f500-0449-11e9-93ec-441353f98f6c.png)
However, as you can see from my snip, my name is filled in by default. Could this be the issue?
2. The output log is not showing any errors:
![image](https://user-images.githubusercontent.com/28734844/50300272-8a3eb580-0449-11e9-9d6d-f4579633a976.png)

**Comment by gioboa** [comment]
Yes, I suppose this is the problem.
The plugin check required fields before execute the Jira request.
The plugin try to manage all the field types, I need to check the report field.
The reporter field in not field list so for sure the plugin can't manage it.
Your reporter field it's custom?

**Comment by LarBearrr** [comment]
Sounds about right. What I'm curious about is that other required fields show up for different types of issues. From what my manager is telling me, the Reporter field is part of the default field schema. 
Does the plugin look for custom fields?

**Comment by gioboa** [comment]
I will check for manage reporter field. :+1:

**Comment by gioboa** [comment]
I decided to manage reporter field in the same way that assignee field. 👍

**Comment by gioboa** [comment]
@LarBearrr 
I published [v 0.11.4](https://github.com/gioboa/jira-plugin/releases/tag/0.11.4)
I hope solve your issue.
Please let me know.
