### ISSUE TITLE
issue: Cannot fetch Jira Issues from different WorkingIssueStatus

### ISSUE THREAD

**Issue by dchennaraidu** [gioboa/jira-plugin#49]
Extension not reading user set **Working Issue Status** [ _jira-plugin.workingIssueStatues_: '_pending_'}

**To Reproduce**
1. Go to **Settings**
2. Click on **User Settings**
3. Find Extensions -> Scroll down to 'Working Project Option'
4. Change to any valid Working Issue
5. Click on bottom bar Jira 'No working Issue bar'
6. By default it shows, 'In progress' not issues found for your user in foobar project

**Expected behavior**
It should show issues related to given WorkingIssueStatus 

**Screenshots**
![image](https://user-images.githubusercontent.com/12108102/50374561-e0f8ea80-0615-11e9-9cb0-0fcc33479e8c.png)

**Comment by gioboa** [comment]
Hi, did you try to restart VSCode?

**Comment by dchennaraidu** [comment]
Code from **src/shared/utilities.ts** (38:43)

```
export const workingIssueStatuses = (): string => {
  let statusList = (getConfigurationByKey(CONFIG.WORKING_ISSUE_STATUSES) || DEFAULT_WORKING_ISSUE_STATUS)
    .split(',')
    .map((status: string) => status.trim())
    .filter((status: string) => state.statuses.some(stateStatus => stateStatus.name.toLowerCase() === status.toLowerCase()));
  return statusList && statusList.length > 0 ? statusList.reduce((a: string, b: string) => (a === '' ? a + `'${b}'` : `${a},'${b}'`), '') : `'${DEFAULT_WORKING_ISSUE_STATUS}'`;
};
```

Why is filter applied there?

**Comment by dchennaraidu** [comment]
> Hi, did you try to restart VSCode?

Yes, I did

**Comment by dchennaraidu** [comment]
> Code from **src/shared/utilities.ts** (38:43)
> 
> ```
> export const workingIssueStatuses = (): string => {
>   let statusList = (getConfigurationByKey(CONFIG.WORKING_ISSUE_STATUSES) || DEFAULT_WORKING_ISSUE_STATUS)
>     .split(',')
>     .map((status: string) => status.trim())
>     .filter((status: string) => state.statuses.some(stateStatus => stateStatus.name.toLowerCase() === status.toLowerCase()));
>   return statusList && statusList.length > 0 ? statusList.reduce((a: string, b: string) => (a === '' ? a + `'${b}'` : `${a},'${b}'`), '') : `'${DEFAULT_WORKING_ISSUE_STATUS}'`;
> };
> ```
> Why is filter applied there?

When ran extension in Debug mode, I found that _state.status = []_

**Comment by gioboa** [comment]
If you find state.status = [] you can use  jira-plugin.additionalStatuses to fill this array. In a normal workflow this array must be populate, if it's not you can use this particular setting.

**Comment by dchennaraidu** [comment]
Yay it working now after setting **jira-plugin.additionalStatuses**, but I had to restart VSCode
