### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by jumpkick** [gioboa/jira-plugin#5]
Some ideas

- Configurable minimum time block to log, i.e. don't log time if time is under 5 minutes
- Change hint over working issue to show the issue title when an issue is being timed (currently it always shows "Set working issue"
- Include the issue ids in the issue selection drop down, currently they show issue title only

**Comment by gioboa** [comment]
I think that are good ideas/fix. :smiley:
I plan these tasks in the next milestone. :v:

**Comment by gioboa** [comment]
@jumpkick I implemented the last feature, minimum tracking time for create Jira worklog.
Have a look [commit](https://github.com/gioboa/jira-plugin/commit/25d0424949e1937da5b996e4960b02e0073c1f9a) 👍

**Comment by jumpkick** [comment]
Haven't tried it yet, but looking at the commit, it looks good
