### ISSUE TITLE
Jira Database issue: issue status displayed differ from jira jql status

### ISSUE THREAD

**Issue by alexandremsouza1** [gioboa/jira-plugin#51]
After the last update stopped working. 
 
Version: 0.11.3.

![1](https://user-images.githubusercontent.com/38253342/50653180-d15f9700-0f6f-11e9-8a2f-fbfa4731c5b6.PNG)
![2](https://user-images.githubusercontent.com/38253342/50653183-d290c400-0f6f-11e9-8d77-f513c53ee3b6.PNG)
![3](https://user-images.githubusercontent.com/38253342/50653191-d45a8780-0f6f-11e9-94c7-efe386e7d892.gif)

**Comment by gioboa** [comment]
Hi @alexandremsouza1,
do you remember which version you had before?
In the last update I touched only README file. :confused:

**Comment by alexandremsouza1** [comment]
It could have been coincidence. 
But my old version was 0.10.4

**Comment by gioboa** [comment]
When you filter by status the plugin execute this Jira jql:
`project = <your_current_working_project_key> AND status = '<selected_status>' ORDER BY status ASC, updated DESC`
If you insert `console.log('jql',jql)` at this [line](https://github.com/gioboa/jira-plugin/blob/440b8f744d466d88950d2f9aafe645ba8740842d/src/shared/select-utilities.ts#L145) you can see which jql will be used.

**Comment by alexandremsouza1** [comment]
Exact! But the status that is appearing in the filter is not the same as the current sprint.
That's weird.
And it also shows that those statuses are being automatically generated by the jira api

**Comment by alexandremsouza1** [comment]
So I do not know what's happening

**Comment by gioboa** [comment]
Did you try to copy and paste the jql generated in Jira web application?it works?

**Comment by alexandremsouza1** [comment]
This procedure I do not know how to execute rsrs.

**Comment by gioboa** [comment]
With this procedure you can perform you custom search

![jira-search](https://user-images.githubusercontent.com/35845425/50685682-7df65300-101a-11e9-905a-5fa502990346.gif)

**Comment by alexandremsouza1** [comment]
![teste](https://user-images.githubusercontent.com/38253342/50686141-462fe100-1003-11e9-9e24-c12e2e4a56d1.gif)

few results.

Note that in sprint there is more status in the print sent earlier

**Comment by gioboa** [comment]
If you insert a console.log(issues) [here](https://github.com/gioboa/jira-plugin/blob/440b8f744d466d88950d2f9aafe645ba8740842d/src/shared/select-utilities.ts#L148)
Do you see any data?

**Comment by alexandremsouza1** [comment]
'Unable to log remote console arguments Output omitted for a large object that exceeds the limits'


I do not know how you take it

**Comment by alexandremsouza1** [comment]
returned 50

**Comment by gioboa** [comment]
ok 👍 
Now if you insert a `console.log('item',items)` (or `console.log('item',items. length)`) [here](https://github.com/gioboa/jira-plugin/blob/8363c690660bb8acc48a7037177b1f349a44ab7c/src/explorer/jira-explorer.ts#L44)
and `console.log('item',items)` (or `console.log('item',items. length)`) [here](https://github.com/gioboa/jira-plugin/blob/8363c690660bb8acc48a7037177b1f349a44ab7c/src/explorer/jira-explorer.ts#L56)
what's the difference from the two console log?

**Comment by alexandremsouza1** [comment]
![capturar](https://user-images.githubusercontent.com/38253342/50689756-12a88300-1012-11e9-8302-432bc5749499.PNG)

First console =  array(22)
second console = item 55

**Comment by alexandremsouza1** [comment]
![2](https://user-images.githubusercontent.com/38253342/50689886-8ea2cb00-1012-11e9-9877-de0af3c8f121.PNG)

First console = array(22)[0]
second console = item 55 pos[10]

**Comment by gioboa** [comment]
maybe the first console.log is not `console.log('items',items)` can you check please?
And even if there are 50 items, no item is present in explorer list?

**Comment by gioboa** [comment]
And even if there are items no one is present in explorer list?

**Comment by alexandremsouza1** [comment]
No, in the explorer list the items are displayed normally.


Item categories are different. In the sprint filter the filters that are in the site appear but in the search filter by filter some non existent filters appear.

![6](https://user-images.githubusercontent.com/38253342/50690667-52bd3500-1015-11e9-8279-a85f5802a1cd.gif)

**Comment by gioboa** [comment]
Maybe I don't understand the problem.
So you ask why in current sprit there are some issues for **Itens Pendentes** and when you filter directly for  **Itens Pendentes** no issue appear?

**Comment by alexandremsouza1** [comment]
Exact

**Comment by gioboa** [comment]
Is the prev console.log('items', items.length) result for **Itens Pendentes** status?

**Comment by alexandremsouza1** [comment]
![10](https://user-images.githubusercontent.com/38253342/50691586-530aff80-1018-11e9-81ec-6798729cebca.PNG)

**Comment by gioboa** [comment]
If you perform this search in Jira Web application
`project = TR AND status = 'Itens Pendentes' ORDER BY status ASC, updated DESC`
how many issues do you find?

**Comment by alexandremsouza1** [comment]
It did not return results, but I realized that if put in English('Itens Pendentes' to 'To do') it works

**Comment by gioboa** [comment]
> It did not return results, but I see that if put in English('Itens Pendentes' to 'To do') it works
Also in Jira web application you have to translate 'Itens Pendentes' to 'To do'? 😮

**Comment by alexandremsouza1** [comment]
In jira application web is English, in the VSCode is mixed (Portugues and English)

**Comment by gioboa** [comment]
In your previous gif I see that if you try for 'Done' it works and find issues with status in portuguese. When you filter for some portuguese status Jira don't find anything. :+1:

**Comment by alexandremsouza1** [comment]
Exactly! My difficulty is knowing what the status in English represents the status in Portuguese, 
for most cases are not literal translations

**Comment by gioboa** [comment]
I will check if there is some relationship between English and Portuguese statuses, maybe some I'd or something else.

**Comment by alexandremsouza1** [comment]
Thank you very much for your attention.

**Comment by gioboa** [comment]
[here](https://github.com/gioboa/jira-plugin/issues/51#issuecomment-451441480)
in the first console you have all statuses
if you open every item, do you find any relationship field?

**Comment by alexandremsouza1** [comment]
I lost where I put the console.log kkk

**Comment by gioboa** [comment]
Hi @alexandremsouza1  
have a look at [this Jira tool](https://confluence.atlassian.com/adminjiraserver073/using-the-database-integrity-checker-861253809.html?_ga=2.175211872.394122513.1546788740-667084326.1546600020) and [this solution](https://community.atlassian.com/t5/Jira-questions/Issue-workflow-status-different-in-query-search-to-status/qaq-p/154619)

**Comment by alexandremsouza1** [comment]
Okay, I do not have administrator permission, but I think it's interesting to leave this post for quest

**Comment by gioboa** [comment]
It's a Jira issue. I close it :+1: it remain in issues history anyway.
