### ISSUE TITLE
Use a subfolder of base Jira installation

### ISSUE THREAD

**Issue by stratosgear** [gioboa/jira-plugin#62]
When setting up my `Base Url` as `https://issues.my.company/subfolder` the plugin tries to login at `https://issues.my.company/rest/api/2/status` producing an error of:

```
Error: {"statusCode":404,"body":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /rest/api/2/status was not found on this server.</p>\n</body></html>\n","headers":{"date":"Mon, 14 Jan 2019 10:03:50 GMT","server":"Apache/2.4.6 (Red Hat Enterprise Linux)","content-length":"215","connection":"close","content-type":"text/html; charset=iso-8859-1"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"issues.my.company","port":443,"hostname":"issues.my.company","hash":null,"search":null,"query":null,"pathname":"/rest/api/2/status","path":"/rest/api/2/status","href":"https://issues.my.company/rest/api/2/status"},"method":"GET","headers":{"authorization":"Basic c2dlXXXXXXXXXXs6UG9XXX3JzbEB2My4=","accept":"application/json"}}}
Error: TypeError: Cannot read property 'split' of undefined
```

**Describe the solution you'd like**
It seems I cannot use `/subfolder` in the base url.   If I try the url of `https://issues.my.company/subfolder/rest/api/2/status` from the browser, it works fine and I get a JSON reply from JIRA.

**Comment by gioboa** [comment]
The solution need more tests.

**Comment by stratosgear** [comment]
Thanks! The new release now can login and get a list of projects.

But you need more. Clicking on an issue opens:

https://issues.my.company/browse/PROJ-123

instead of: 

https://issues.my.company/SUBFOLDER/browse/PROJ-123

Should I create a new issue, or is this still part of this one?

**Comment by gioboa** [comment]
Now are you using v 0.12.1?

**Comment by gioboa** [comment]
ok, now I fix also the other issue (Clicking on an issue opens).

**Comment by gioboa** [comment]
Please give me your feedback. Thanks.

**Comment by stratosgear** [comment]
Just to give some immediate feedback, this latest issue, browsing to a Jira issue, has been fixed!

Let me play more with it.  Thanks for the quick turnround.
