### ISSUE TITLE
Receiving "Error: getaddrinfo ENOTFOUND" on upgrade to 0.12.0

### ISSUE THREAD

**Issue by dstrunk** [gioboa/jira-plugin#64]
**Describe the issue**
On upgrade to 0.12.0, my JIRA integration has been broken; output says "Error: getaddrinfo ENOTFOUND". I've downgraded to 0.11.4 and can confirm that the same credentials are working for this version. I'm not able to share our Jira instance, but here is an example of the URL: `http://jira.example.com:8080`. Perhaps it's related to the refactoring in 96896cd, but that's just a guess …

I tried adding `"http.proxyStrictSSL": false` in user settings, but that did nothing.

**To Reproduce**
1. Upgrade to version 0.12.0
2. Add credentials with a URL similar to `http://jira.example.com:8080`
3. Attempt authentication, see error

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - VSCode 1.30.2
- Jira-plugin version 0.12.0

**Additional context**
JIRA is self-hosted and on a corporate network.

**Comment by gioboa** [comment]
Thanks for your feedback. 👍 
I'm really sorry for the inconvenience.
I will release an hotfix soon.
