### ISSUE TITLE
Working project isn't set.

### ISSUE THREAD

**Issue by TonyCMCC** [gioboa/jira-plugin#65]
when i configure jira-plugin，it tell me "Working project isn't set."
how can i deal it?

**Comment by gioboa** [comment]
Hi in the status bar you have the possibility to setup the current working project. 👍
Have a look [here](https://github.com/gioboa/jira-plugin/blob/master/README.md#set-working-project)

**Comment by TonyCMCC** [comment]
that's great! this plugin is very useful,thanks a lot.
please make the alert message more detail for easy to use

**Comment by gioboa** [comment]
Thanks for your feedback! 👍 😄
