### ISSUE TITLE
Escape project name in JQL Queries

### ISSUE THREAD

**Issue by noodlensk** [gioboa/jira-plugin#71]
We have a project in our Jira called "IN". When I'm trying to get a list of issues in this project - I'm getting this error:
`"Error in JQL Query: Expecting either a value, list or function but got 'IN'. You must surround 'IN' in quotation marks to use it as a value`

**Comment by gioboa** [comment]
Fixed in [v 0.12.3](https://github.com/gioboa/jira-plugin/releases/tag/0.12.3)
