### ISSUE TITLE
refactoring: Separate test environment from production

### ISSUE THREAD

**Issue by knicefire** [gioboa/jira-plugin#77]
While under development, running tests messes up with production configuration and replaces it with mocked data

Detect scenario when the code is ran under the test, to prevent messing up with "production" settings

**Comment by gioboa** [comment]
I use [VsCode insiders](https://code.visualstudio.com/insiders) so I didn't know about this problem.
It's an important issue to solve.

**Comment by knicefire** [comment]
Can you reproduce it with regular VsCode? 
Probably it's doesn't work just in my case

**Comment by gioboa** [comment]
With normal VsCode I have exactly the problem that you described :+1:

**Comment by gioboa** [comment]
The plugin will backup settings before execute tests and it will restore settings after tests. 👍
