### ISSUE TITLE
refactoring: folder/workspace based configuration instead of globalState

### ISSUE THREAD

**Issue by knicefire** [gioboa/jira-plugin#79]
Consider removing the need for globalState access, as well as setting target to global [here](https://github.com/gioboa/jira-plugin/blob/develop/src/services/configuration.service.ts#L50)

All projects are folder based or workspace based so let's be able to set different configuration for each, and this still doesn't prevent user to set global configuration

**Comment by gioboa** [comment]
Hi @knicefire,
I did a little test, workspace settings "win" against the global VsCode settings so for every workspace you can have different configuration. 
Only password is stored in hidden global state and the key so the Jira baseurl + username so you can't have workspace with same baseurl and different user. :cry:

**Comment by knicefire** [comment]
Thanks.

I think this is fine, a long as we have separate workspace configuration.

**Comment by gioboa** [comment]
I close it for the moment. Anyway workspace config "win" against user config.
