### ISSUE TITLE
Allow the timer to run, even if VS Code is not in focus

### ISSUE THREAD

**Issue by Sigggi** [gioboa/jira-plugin#8]
Great work so far. Thank you.

It would be nice to be able to track the time I have worked on an issue, not just the pure coding time.

Maybe with a setting?

**Comment by gioboa** [comment]
Hi, I'm really happy you like the plugin. :smile: 
I think your idea is a good improvement. 
We can create a setting for manage both cases: 
- pure code time 
- "general" time
What do you think?
How we can call the two behaviors?

**Comment by gioboa** [comment]
name: **trackingTimeMode**
values:
- always
- vsCodeFocus

@Sigggi  What do you think?

**Comment by Sigggi** [comment]
Sound good!
Should be understandable for all, with a litte comment for the setting.

**Comment by jumpkick** [comment]
@Sigggi I'm also working on a patch that would add time away back to the counter if you came back to VScode within the timeout period.   i.e. If you come back to VSCode within 20 minutes of it becoming inactive, it would add whatever amount of time you were away, if you were away longer it would not add any time when you came back.  That way if you go off to a two hour meeting or leave for the day, it doesn't log time.   This was my first attempt at that: https://github.com/jumpkick/jira-plugin/commit/5ae2a5f3681c6dd7a688f15361453c95a8a53fdb#diff-0922ea55b32cc9b36de80d4ae7b4bc1e, but it needs to be fixed up...  Hopefully, I'll get a chance later on this week to work on it.

**Comment by Sigggi** [comment]
This is awesome! Never thought of that myself, but it makes perfectly sense.

Looking forward to it.

**Comment by gioboa** [comment]
Implemented this feature [commit](https://github.com/gioboa/jira-plugin/commit/aca8c38b1a5b2dd32170cda6f9e46b5845aa7d4d) :stuck_out_tongue_winking_eye:

**Comment by jumpkick** [comment]
@Sigggi release 0.6.0 adds hybrid time tracking mode that behaves as I described...  check it out :smile:

**Comment by Sigggi** [comment]
@jumpkick Works as described. Thanks!

One minor thing: If I lock the screen the timer keeps counting. I just have to remember to switch focus to something else, before locking. Would be cool, if there is an easy patch for that.

But nonetheless, I recommended this extension to my coworkers, mainly because of this new feature.
