### ISSUE TITLE
Copy to clipboard does not work

### ISSUE THREAD

**Issue by it0243** [gioboa/jira-plugin#80]
Issue Type: <b>Bug</b>

Copy to clipboard does not work and throws an error:
"Check logs in Jira Plugin Terminal output", but I cannot see anything in Output window.

I have tried it with 2 different ways: 1. from Jira Explorer using the jira issue context menu and 2. using a keyboard shortcut for the working issue.

I have the latest version of VS Code and the Jira plugin and my OS is Ubuntu 18.0.4.

Extension version: 0.12.4
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-5400K APU with Radeon(tm) HD Graphics (2 x 2310)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (1.08GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gioboa** [comment]
Hi @it0243 ,
did you look [here](https://github.com/gioboa/jira-plugin/issues/34)?
It's strange because copy command don't throw any error, for sure it's something different.

**Comment by it0243** [comment]
Correct, after installing **xclip** and restarting VS Code the Copy feature now works. Thank you!

Do you think that this dependency could be added to the plugin documentation at the Copy to clipboard section?

**Comment by gioboa** [comment]
it's an issue of copy-paste lib.
I think that this closed issue is enough. :+1:
