### ISSUE TITLE
feat: git branch management

### ISSUE THREAD

**Issue by knicefire** [gioboa/jira-plugin#82]
Would be nice to have deeper integration with Git capabilities

a. Ability to see the list of branches for the ticket
b. Ability to create a branch for the ticket in the ticket menu. The source branch needs to be suggested
c. Suggest switching to the ticket branch in case of changing ticket/project

All of the above would give the developer more control over the ticket processing.

**Comment by gioboa** [comment]
In the next days I will implement the b feature. I've created a branch for it.

**Comment by knicefire** [comment]
Cool. Looking forward to it

**Comment by gioboa** [comment]
_Feature b_

I've done the implementation. What do you think?
I used VsCode git commands and unfortunately there isn't the possibility to set the branch name by code.

![ezgif-5-71acef9a3208](https://user-images.githubusercontent.com/35845425/53185326-0d71b880-35ff-11e9-9108-5bbff90cf46f.gif)

**Comment by knicefire** [comment]
Looks cool!

Can you pre-fill it? So the user doesn't have to and is able to change it
if needs it

**Comment by gioboa** [comment]
Unfortunately in the VsCode command there isn't the possibility to pre-fill it. I will check better...

**Comment by gioboa** [comment]
Feature a and c are really similar, I've done one command that call native git checkout.
This command allow you to create a new branch or list you all available branch to checkout.
No pre-fill value can be passed. 😢

**Comment by knicefire** [comment]
No worries.
Having an ability to create a new branch is already a success
