### ISSUE TITLE
feat: jira notifications

### ISSUE THREAD

**Issue by knicefire** [gioboa/jira-plugin#83]
In Jira there is a new feature called notifications. 

And since users are spending most of the time in VS Code, it would be nice if we could receive notifications right to it.

It'd give our users the competitive advantage over others because there is less need of switching context.

**Comment by gioboa** [comment]
Which kind of notification would you like?

**Comment by gioboa** [comment]
I searched for notification API. Did you mean [Activity stream](https://developer.atlassian.com/server/framework/atlassian-sdk/consuming-an-activity-streams-feed/)?

**Comment by knicefire** [comment]
I don't know how it's called internally. 
It looks like a a notification in the aside panel. 
It get's you informed whenever any activities on your tasks happen. Or if someone mentions you somewhere in a comment. 

![notification](https://user-images.githubusercontent.com/2177810/52527288-bf8bb500-2cce-11e9-9435-d074bf064d29.gif)

**Comment by gioboa** [comment]
JIRA web application retrieve the date from `baseUrl/gateway/api/notification-log/api/2/notifications`. If I call this URL from the plugin return 401, from the web all works well.

**Comment by knicefire** [comment]
That's because authentication is required. 

I'll take a look but don't have spare time as of now :(

**Comment by gioboa** [comment]
This [commit](https://github.com/gioboa/jira-plugin/commit/81e2f94c15563613588644e8c4b4cf8d1b21a70b) add notifications API. 🎉 
The code create a new cloud session and call notifications cloud API. 👍

**Comment by knicefire** [comment]
This is awesome!

**Comment by gioboa** [comment]
This feature is in develop branch ready for the next major release. :+1:
