### ISSUE TITLE
Default Filter does not return data.

### ISSUE THREAD

**Issue by jcstorino** [gioboa/jira-plugin#84]
**Describe the issue**
Default filter does not return data.

**To Reproduce**
1. Go to 'Jira Panel'
2. Click on 'Three points (more actions) / My Issues filtered by status / Pendent itens'
3. Wait refresh
4. Nothing is displayed

**Expected behavior**
The issues assigned to me and in the Pendent itens status.

**Screenshots**
![image](https://user-images.githubusercontent.com/19559870/52502620-5fabe600-2bca-11e9-99c5-893f56008670.png)

Error: Error: Wrong parameter. No issues found for SD88M project.
Error: {"statusCode":400,"body":{"errorMessages":["O valor 'Itens Pendentes' não existe para o campo 'status'."],"warningMessages":[]},"headers":{"server":"Atlassian Proxy/1.13.6.2","cache-control":"no-cache, no-store, no-transform","content-type":"application/json;charset=UTF-8","strict-transport-security":"max-age=315360000; includeSubDomains; preload","date":"Fri, 08 Feb 2019 19:51:14 GMT","atl-traceid":"92148c091fe2b3ab","x-aaccountid":"5bd055821968013b778a48c6","x-arequestid":"52ccc214-77fd-4f26-80d8-6fe99491817e","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","timing-allow-origin":"*","x-ausername":"julio.storino","x-content-type-options":"nosniff","connection":"close","set-cookie":["atlassian.xsrf.token=7dbece4d-e3f3-4b4e-9b21-64060d44e805_a9becf9858992fc40af4e2712dd144f36ae98819_lin; Path=/; Secure"],"x-seraph-loginreason":"OK"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"comerc.atlassian.net","port":443,"hostname":"comerc.atlassian.net","hash":null,"search":null,"query":null,"pathname":"/rest/api/2/search","path":"/rest/api/2/search","href":"https://comerc.atlassian.net/rest/api/2/search"},"method":"POST","headers":{"authorization":"Basic anVsaW8uc3Rvcmlub0Bkb2M4OC5jb20uYnI6IVN0cm92YXZhQDIy","accept":"application/json","content-type":"application/json","content-length":140}}}

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Version 10.14.3 (18D42)

**Comment by gioboa** [comment]
Hi @jcstorino ,
In the error there is the resolution: `O valor 'Itens Pendentes' não existe para o campo 'status'.`
Please check the default jql :+1:

**Comment by jcstorino** [comment]
My jira has custom status ... in Brazilian Portuguese.
![image](https://user-images.githubusercontent.com/19559870/52503436-b61a2400-2bcc-11e9-811c-8d69417ff763.png)

For JQL, i have...
"jira-plugin.defaultJQLSearch": "project = 'WORKING_PROJECT' AND sprint in  OpenSprints() AND assignee = currentuser() ORDER BY status ASC, updated DESC",

The filter "Default JQL Search" works fine !
![image](https://user-images.githubusercontent.com/19559870/52503507-df3ab480-2bcc-11e9-9c90-0d134fcaa931.png)

**Comment by gioboa** [comment]
So, it was a problem in the JQL? Now it works fine?

**Comment by jcstorino** [comment]
No !  ( sorry - by translator )

I'll try to be clearer.

Is JQL only for the default filter ?  ( Default JQL Searcher )

Can I change the JQL of the other queries? from 1 to 7 ? how do I do that ?

When I select the 7 filter, nothing is returned !

**Comment by gioboa** [comment]
Default jql is customizable from settings. You can define favourites filters inside Jira and use them from the plugin option 8.

**Comment by gioboa** [comment]
Option 7 execute this Jql 
`project = 'working_project' AND status = 'selected_status' AND assignee in (currentUser()) ORDER BY status ASC, updated DESC`

**Comment by gioboa** [comment]
Solved.

**Comment by jcstorino** [comment]
Sorry, but I can not understand.

In my Jira the status is "Itens Pendentes" and in the plugin it does not find anything with this status!
![captura de tela 2019-02-11 as 08 49 48](https://user-images.githubusercontent.com/19559870/52558712-6610ac80-2dda-11e9-847a-2aa624e85402.png)


Where do I have to change to adjust the status name? 
How can I see the real name of the status internally in Jira?

I need to find out where the problem is!

**Comment by gioboa** [comment]
Maybe can be related to #51 ?

**Comment by gioboa** [comment]
@jcstorino did you find a solution for this issue?

**Comment by jcstorino** [comment]
No, I have not found a solution yet. Portuguese language status does not match to the filters in this extension.

![captura de tela 2019-02-26 as 13 57 23](https://user-images.githubusercontent.com/19559870/53431115-a5401f80-39ce-11e9-96bc-dee01282c337.png)

![captura de tela 2019-02-26 as 13 59 20](https://user-images.githubusercontent.com/19559870/53431196-cbfe5600-39ce-11e9-86b0-f8e9a2be32d1.png)

**Comment by gioboa** [comment]
If you go into the 1623 issue, which status do you have? Could you post here also the status list page? I think it's an amministrator page...

**Comment by gioboa** [comment]
Which status have SD88M-162?
I notice in my environment that in every Kannan coloumn can contain more than one status. Here the colounm name is 'items pendientes' but which status contains?

**Comment by gioboa** [comment]
No update in last 7 days. Closed.
