### ISSUE TITLE
Option to disable time tracking

### ISSUE THREAD

**Issue by richard-riverford** [gioboa/jira-plugin#85]
We don't use the time tracking feature of Jira, so having a tracker running in VS Code is pointless, and being prompted to update a ticket with time tracking information is annoying.

It would be great to add another time tracking option - `never` - to complement `always`, `hybrid` and `vsCodeFocus`. This would turn-off time tracking completely and not prompt the user to update a Jira ticket with time-tracking information when switching to a different ticket.

**Comment by gioboa** [comment]
Hi @richard-riverford , 
your issue have sense. 
initially `Enable Working Issue` setting was introduce for disable time tracking.
Nowadays with "Working Issue functionality" there are more features.

**Comment by JohannesMattsson91** [comment]
I would really like that option as well, the time track feature only made me disable the entire "working issue" feature to disable the prompt.

**Comment by gioboa** [comment]
I released [v 0.13.1](https://github.com/gioboa/jira-plugin/releases/tag/0.13.1).
This version add `never` option in time tracking setting.
Please give me you feedback. Thanks. 👍

**Comment by richard-riverford** [comment]
Wow, fast work! Thanks for this; it looks perfect! 👍

**Comment by JohannesMattsson91** [comment]
Works like a charm when switching branches between existing branches and new branches.
