### ISSUE TITLE
issue: unable to verify the first certificate

### ISSUE THREAD

**Issue by probfacile** [gioboa/jira-plugin#90]
**Describe the issue**
Error: Error: unable to verify the first certificate and cannot figure out what is the problem. Looks like there is a problem with self hosted jira, self signed certificate but I am not an expert of this

**To Reproduce**
I think, self host jira, self sign certificate and try just witzard configuration and error will pop out

**Expected behavior**
Should work

**Desktop (please complete the following information):**

Versione: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Data: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Log**
Error: Error: unable to verify the first certificate
Error: Error: unable to verify the first certificate
Error: Error: unable to verify the first certificate
Error: Error: unable to verify the first certificate

**Comment by gioboa** [comment]
Hi @probfacile ,
have a look at [this issue](https://github.com/gioboa/jira-plugin/issues/1) maybe are related. 
I think you can solve the problem by using [this extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca)

**Comment by probfacile** [comment]
I am on Linux ubuntu 18.04 not windows

**Comment by gioboa** [comment]
Sorry you are right.
Please have a look at [VsCode docs](https://code.visualstudio.com/docs/setup/network) maybe this settings can solve your issue.

**Comment by probfacile** [comment]
disabled it and still same problem

**Comment by gioboa** [comment]
Unfortunately this issue isn't under my control.
It's a VsCode error. 
Try to follow the [docs](https://code.visualstudio.com/docs/setup/network) to solve the issue. :disappointed:

**Comment by probfacile** [comment]
neither mine, I don't find any help anywhere.
these docs are for experts, i don't find anything I can follow there.
if anyone has a clue please link/help here... otherwise I just give up

**Comment by gioboa** [comment]
The problem occur in the plugin installation?
Did you fill all the proxy settings inside VsCode?

https://cloud.githubusercontent.com/assets/14846203/12105548/cc12701c-b390-11e5-9928-58eeed452b9c.PNG

**Comment by probfacile** [comment]
I don't use a proxy to connect.
The https domain has self certificate, and it doesn't verify it

**Comment by gioboa** [comment]
Please execute this test.

from VSCode docs:
`you can tell VS Code to ignore all certificate errors using the --ignore-certificate-errors command line flag. Warning: This is dangerous and not recommended, since it opens the door to security issues.`

so in the terminal run: `code . --ignore-certificate-errors` 

if it works, we will find a way to install the certificate in Ubuntu. 👍

**Comment by probfacile** [comment]
For just a test i started with this unsafe options and still Error: `Error: unable to verify the first certificate`

**Comment by gioboa** [comment]
Thanks for your test. I will check how solve this problem. 😞

**Comment by gioboa** [comment]
@probfacile  in [v 0.14.1](https://github.com/gioboa/jira-plugin/releases/tag/0.14.1) I've added the possibility to specify certificate inside every request.
[Here](https://github.com/gioboa/jira-plugin/blob/7e373950218bf9885ee567934761225a3fbd845b/package.json#L129) the new settings.
Please test it and give me a feedback. 👍

**Comment by probfacile** [comment]
ok I will try even if I am unsure how to download the domain certificate from chrome

**Comment by gioboa** [comment]
Maybe [this post](https://superuser.com/questions/1291416/download-pem-via-browser-only) can help you.

**Comment by probfacile** [comment]
Something weird is happening then because i did exactly all described and still `Error: Error: unable to verify the first certificate`

**Comment by gioboa** [comment]
So you download the cert in your machine, then you modify the new configuration with the cert full path, correct?
From VsCode you can open a dev tool like chrome 😄 this can be really useful.

![screenshot 2019-02-26 at 09 19 28](https://user-images.githubusercontent.com/35845425/53397537-a3169a80-39a7-11e9-8780-00a8c0d71d5c.png)

**Comment by probfacile** [comment]
i've downloaded certificate in multiple ways, tested without conversion nothing, then tested with conversion:

`openssl x509 -in _my_certificate.com.crt -out _my_certificate.com.pem -outform PEM`
and didn't work either.

I also tryed developer tools many times but nothing more that output is there:

```notificationsAlerts.ts:40 Error: Check logs in Jira Plugin terminal output.
t.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | e.fire | @ | event.ts:567
  | t.notify | @ | notifications.ts:113
  | t.notify | @ | notificationService.ts:52
  | (anonymous) | @ | mainThreadMessageService.ts:84
  | e._showMessage | @ | mainThreadMessageService.ts:45
  | e.$showMessage | @ | mainThreadMessageService.ts:39
  | t._doInvokeHandler | @ | rpcProtocol.ts:390
  | t._invokeHandler | @ | rpcProtocol.ts:375
  | t._receiveRequest | @ | rpcProtocol.ts:295
  | t._receiveOneMessage | @ | rpcProtocol.ts:225
  | (anonymous) | @ | rpcProtocol.ts:100
  | e.fire | @ | event.ts:567
  | s | @ | ipc.net.ts:295
  | (anonymous) | @ | ipc.net.ts:302
  | e.fire | @ | event.ts:567
  | a | @ | ipc.net.ts:103
  | _socketDataListener | @ | ipc.net.ts:132
  | emit | @ | events.js:182
  | addChunk | @ | _stream_readable.js:279
  | readableAddChunk | @ | _stream_readable.js:264
  | Readable.push | @ | _stream_readable.js:219
  | onread | @ | net.js:636
```

**Comment by gioboa** [comment]
mmm you can see at list the task list? or you can't see anything?

**Comment by gioboa** [comment]
Could try to replace the code at [this line](https://github.com/gioboa/jira-plugin/blob/a4a61cf4f05586991df33f9beea15961ebb33264/src/shared/jira-instance-patch.ts#L71) ?
like this:
`options = { ...options, agentOptions: { ...certificate } };`
now the certificate settings is in the root, try to wrap it inside agentOptions.
I get this info [here](https://github.com/request/request#using-optionsagentoptions)
I did not have the environment to test the solution. Thanks 👍

**Comment by probfacile** [comment]
I tried your line, also restarted and nothing better.
I can say the certificate is a RapidSSL one.

**Comment by gioboa** [comment]
Thanks for your test. 👍
I will have a look at RapidSSL to understand something.
Anyway, if you have time and possibility, you can debug the extension (first method of the previous post) and try to understand what's wrong.
The plugin need to pass the certificate in the request, this is the problem.

**Comment by probfacile** [comment]
![image](https://user-images.githubusercontent.com/34299822/53475129-79c14180-3a6f-11e9-8e89-ac0bcb95a108.png)
I console.logged options after your line change and looks correct

**Comment by gioboa** [comment]
👍 The problem is how is the correct way to pass RapidSSL to the request.
In the error we have `first certificate`, maybe you have to pass more than one certificate to the server.
If you open Jira web application from chrome, how many certificates do you see in dev tools - tab security?

**Comment by probfacile** [comment]
i see it's  only 1 and is a *.domain.com because it's jira.domain.com

**Comment by gioboa** [comment]
I checked my company self hosted Jira web application and I have GoDaddy certificate.
<img width="472" alt="screenshot 2019-02-27 at 10 00 51" src="https://user-images.githubusercontent.com/35845425/53478334-d7a55780-3a76-11e9-864c-6ad8d5c6b424.png">
I have also a Atlassian cloud Jira:
<img width="472" alt="screenshot 2019-02-27 at 10 00 51" src="https://user-images.githubusercontent.com/35845425/53478413-0d4a4080-3a77-11e9-97aa-14b734c56b11.png">
I have macOS and also Ubuntu and from both I can connect to them.
In my Ubuntu 16.0 I didn't do any configuration.
Every https has one or more certificates so I think can be something relative to this type of certificate?

**Comment by gioboa** [comment]
Only for test purpose...
Did you try with a Windows machine?

**Comment by probfacile** [comment]
I only have ubuntu 18.04 machine for test. chrome says the same... it's valid and secure.
somehow jira plugin is not working... I might try another jira plugin to see if it connects.

**Comment by probfacile** [comment]
well another plugin works perfectly (doesn't do the same as your):
![image](https://user-images.githubusercontent.com/34299822/53481764-21de0700-3a7e-11e9-9cea-2dff5e790fb1.png)

**Comment by gioboa** [comment]
I will investigate, can you give me the name of this plugin?

**Comment by probfacile** [comment]
jira issues

**Comment by gioboa** [comment]
It's really funny, the author clone my repo and create his how plugin, but the code was really similar to mine. Now I check what he done. 😄

**Comment by gioboa** [comment]
Please modify 
`~/.vscode/extensions/gioboa.jira-plugin-0.14.1/out/src/http/jira-instance-patch.js`
and **before** line 71 `return jiraInstance. ... ... ...` add `options.strictSSL = false;`. Thanks. 👍

**Comment by probfacile** [comment]
Tried and didn't change anything

**Comment by gioboa** [comment]
Did you restart VsCode? have you got a console.log ?

**Comment by probfacile** [comment]
![image](https://user-images.githubusercontent.com/34299822/53486506-307deb80-3a89-11e9-935f-e1f628439fc2.png)
yes

**Comment by gioboa** [comment]
Please delete agentOption property before return `delete options.agentOptions` thanks.

**Comment by probfacile** [comment]
I already tried to comment the object assign for options... is the same i think... and didn't work
![image](https://user-images.githubusercontent.com/34299822/53486822-1c86b980-3a8a-11e9-9058-0f998d074193.png)

**Comment by probfacile** [comment]
hmmm wait... i just did config credential again and started working... wait  i test around (there is no need for agent certificate)

**Comment by probfacile** [comment]
i confirm the row `options.strictSSL = false;` does the difference (without certificate)

**Comment by gioboa** [comment]
So the final code is `options.strictSSL = false;` without agentOptions, settings and bla bla bla?
Now could you change your [review](https://marketplace.visualstudio.com/items?itemName=gioboa.jira-plugin#review-details) please? 
Thanks. 👍

**Comment by probfacile** [comment]
Yes i will change asap... just need time to check around.

**Comment by gioboa** [comment]
Yes, in the next release I will replace the agentOptions setting with a Boolean for enable/disable strictSSL :+1:

**Comment by gioboa** [comment]
With this [commit](https://github.com/gioboa/jira-plugin/commit/5033daf8b3df6ac635eec0cc9b5befe30b429bbb) I added strictSSL setting.
Ready for the next release.
