### ISSUE TITLE
Is there a way to filter the projects with a custom filter?

### ISSUE THREAD

**Issue by probfacile** [gioboa/jira-plugin#91]
**Is your feature request related to a problem? Please describe.**
When I open Project list to set working project, I would like to have a custom filter to see only my team projects.

**Describe the solution you'd like**
Maybe also a JQL search for this, where is put `project IN ('ABC', 'DEF', 'QWE', 'ASD') ORDER BY updated ASC

**Describe alternatives you've considered**
not sure

**Additional context**
There might be a problem when you have a lot of pojects in the domain, and you only want to see yours that are like 10 and select the working project for each open code window.

**Comment by gioboa** [comment]
The plugin use this [Jira API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-api-3-project-get) maybe there is another way to get all the project.
I also notice that this API is marked as deprecated.

**Comment by probfacile** [comment]
What about filtering the result object with client configured array in javascript? something like
myprojects = ['ABC', 'CDE'];
`results.filter(i => myprojects.includes(i.key]);`

**Comment by gioboa** [comment]
Yep, I thought an implementation like this. :+1:
This setting can be useful for some cases.

**Comment by gioboa** [comment]
I will include it in the next release.

**Comment by probfacile** [comment]
Thank you!

**Comment by probfacile** [comment]
ah well i really hoped it would be projects to show... because i have 40 projects growing wich i would like to see only 5 of them i work on :cry:

**Comment by gioboa** [comment]
With this url `https://xxx.domain.com/rest/api/2/project` you can get all projects in json format.
From json you can extract all the project key and copy them into the plugin setting.
I did hideProjects and not showProjects because if you create a new project, you have to remember to add the key into this setting and also showProjects is not backward compatible. Sorry.

**Comment by probfacile** [comment]
ok i will try this solution thx

**Comment by probfacile** [comment]
if you can curl it you get something like:

`curl https://xxx.domain.com/rest/api/2/project | jq .[].key -cMr | egrep -v 'KEY1|KEY2|KEY3' | tr '\n' ', '  | sed 's/,$/\n/'`

**Comment by gioboa** [comment]
v 0.19.0 I added projectsToShow setting. Here you can define only the projects to include. The plugin keep, from all project list, only the project keys you define.
