### ISSUE TITLE
issue: done subtasks ends up under "To do" in explorer view

### ISSUE THREAD

**Issue by mheden** [gioboa/jira-plugin#93]
**Describe the issue**
It seems like Subtasks that are done are still shown under "To do" in the explorer view if the main task is not done.

**To Reproduce**
1) Create a task
2) Add sub tasks
3) Close sub tasks
4) The sub tasks are still shown under "To do"

**Expected behavior**
The sub tasks are shown under done. I understand that it is a bit tricky where to put them since the main task is not done.

**Desktop (please complete the following information):**

Version: 1.32.0-insider (user setup)
Commit: ce073b0076ac2f69faf2c609af72f9b81506c791
Date: 2019-02-27T06:17:47.743Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by gioboa** [comment]
Hi @mheden , you are right.
The plugin consider task status and don't check subtask one.
If subtask have different status, I can remove it "under" the parent task and insert into a correct position. In the subtask label I can refer to the parent task. 
What do you think?
I will solve the issue. Thanks. 👍

**Comment by mheden** [comment]
That would be perfect! Thanks!

**Comment by gioboa** [comment]
I implemented the solution and look like this:

<img width="407" alt="screenshot 2019-03-01 at 15 20 02" src="https://user-images.githubusercontent.com/35845425/53643983-c3f41f80-3c35-11e9-9949-3ca55b0c5023.png">

I also added a setting for chose flat list (old behavior) or grouped list.

**Comment by gioboa** [comment]
Version [0.15.1](https://github.com/gioboa/jira-plugin/releases/tag/0.15.1) solved this issue.
