### ISSUE TITLE
issue: Copy Jira Key+Summary not working on ubuntu 18.04

### ISSUE THREAD

**Issue by probfacile** [gioboa/jira-plugin#94]
**Describe the issue**
Copy Jira Key+Summary not working on ubuntu 18.04

**To Reproduce**
Copy Jira Key+Summary and paste it anywhere, the clipboard is empty

1. Go to 'Jira explorer'
2. Right Click on 'issue'
3. Copy Jira Key+Summary
4. nothing is in clipboard

**Expected behavior**
should put something in clipboard

**Desktop (please complete the following information):**

Versione: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Data: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Log**

**Comment by gioboa** [comment]
Please, have a look at this closed issue #80

**Comment by probfacile** [comment]
but vscode button to copy desktop informations just works without anything installed

**Comment by gioboa** [comment]
Which button are you looking at?
Can you give me a screen?
Under the hood I use a lib to copy to clipboard. This lib needs xclip on Ubuntu.

**Comment by probfacile** [comment]
In fact i think you're doing it wrong... must check vscode source to check how do they copy without addons.. you go in vscode help > informations.. click copy button and it works

**Comment by gioboa** [comment]
Thanks for your feedback. 👍

**Comment by gioboa** [comment]
Solved in [v 0.15.2](https://github.com/gioboa/jira-plugin/releases/tag/0.15.2)
