### ISSUE TITLE
Authentication fails with basic Auth

### ISSUE THREAD

**Issue by JensEger** [gioboa/jira-plugin#95]
We use a local Jira Instance with connected Active Directory as Jira User Directory. Additionally we use EasySSO Plugin for logging into Jira. When I configure this VSCode Plugin with my Windows Credentials i receive an Error (see attached file).
Can you enable Windows Authentication? It would be really great 👍

**Comment by gioboa** [comment]
Hi @JensEger , 
I will check the txt. 👍

**Comment by gioboa** [comment]
@JensEger did you solve your issue?

**Comment by JensEger** [comment]
@gioboa Thank you for your lightning-fast response 👍 The hint to #26 helped alot. Since we log in with Windows auth, we dont have to enter our credentials manually. I logged out and logged in manually and I got the captcha! I solved it and now the Plugin works. 
Again: thanks a lot!
