### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by therblack** [gioboa/jira-plugin#96]
Hi

we run Jira internally.  When I enter the URL and credentials (the same ones I use when logging in a browser) I just get an error 'Error: Check logs in Jira Plugin terminal output.'

When I checked the debug console I see lines like this:

Error: Error: unable to get local issuer certificate

Any suggestions as to what I should do?

thanks

**Comment by gioboa** [comment]
Hi, try to set jira-plugin strictSSL setting to false, restart VsCode and try again.

**Comment by gioboa** [comment]
Did you solve the issue?

**Comment by therblack** [comment]
It did!  Thanks for your quick response, I'm looking forward to using this
