### ISSUE TITLE
issue: When you have multiple code windows open, it's buggy

### ISSUE THREAD

**Issue by probfacile** [gioboa/jira-plugin#97]
**Describe the issue**
Changing project in one windows doesn't change in other window, but it tryes to list "working issue" from last project changed

**To Reproduce**

1. Open folder in one vscode window
2. To be sure go to file -> open recent and shift+click another project folder
3. Select 1 project in first window
4. Select 1 project in second window
5. Select 1 working issue in second window
6. Check first window will tell you correcty project
7. Click on No working issue on first window it will list issues from project of second window

**Expected behavior**
List correct issues in current working window

**Screenshots**
![image](https://user-images.githubusercontent.com/34299822/53949301-0e5c1d00-40ca-11e9-9c5c-8f42640e2170.png)

**Note**
Project is PMU but messages say HMU

**Desktop (please complete the following information):**

Versione: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Data: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Log**
Error: Error: Wrong parameter. No issues found for PMU project.

**Comment by gioboa** [comment]
Hi @probfacile ,
this append because working project is read from configuration before read working issues.
The solution is read the project at start up once and change only if window event trigger it.
Nice catch. 👍

**Comment by probfacile** [comment]
Also if you then change project on other window after selecting a working issue, you will have a new project and working from the other window project

**Comment by gioboa** [comment]
Solved in [v 0.15.2](https://github.com/gioboa/jira-plugin/releases/tag/0.15.2)
