### ISSUE TITLE
issue: Still something weird with multiple code windows

### ISSUE THREAD

**Issue by probfacile** [gioboa/jira-plugin#98]
**Describe the issue**
It's really unclear what happens: If i open a new window it will open with project selected from previous window, and also the working issue timer if started. Same happens when closing a window stick on a project, select project in another, reopening that window will select project from other window.
Also when you switch back project where you had a working issue, the timer is there and increments, but when you stop working it will not ask to save to jira.

**To Reproduce**

1. Setup project + working issue on current window
2. Go to file -> open recent and shift+click another project folder

**Expected behavior**
I would like to save project for every open code project or folder. Or at least start with no project and no working issue.

**Desktop (please complete the following information):**
Versione: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Data: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

**Log**
n/a

**Comment by gioboa** [comment]
Hi,
maybe start with no project and no working issue can be the solution. anyway you can define manually custom workspace settings, if you want. Thanks.

**Comment by gioboa** [comment]
@probfacile did you try the solution?

**Comment by probfacile** [comment]
I think the problem is saving the working project into settings...
maybe there could be a pair as this:
```"/home/user/projectA" : "PJA",
"/home/user/projectB" : "PJB",```
automatically made somewhere by plugin

**Comment by probfacile** [comment]
Looks like your solution is correct way...
You should not set working project into main settings automatically then.
I might want to setup them in my projects or leave it blank to start as no project selected

**Comment by gioboa** [comment]
Ok, I will check if there is an VsCode API for read/write from workspace `.vscode/settings.json`.
If there is, I will move project and workingProject settings into it.

**Comment by probfacile** [comment]
oops :) i closed in error
