### ISSUE TITLE
issue: Time not being tracked on Jira

### ISSUE THREAD

**Issue by mithrend** [gioboa/jira-plugin#99]
When I stop working on an issue, time is not tracked.

1. Go to working issue at the bottom of the editor
2. Change it from working issue (the time is being tracked correctly in the gui) to No working issue

**Expected behavior**
A vscode notification asking me if I want to log the time to Jira with an option to add a comment.

**Actual behaviour**
Nothing get's logged and no notification appears. The current working issue does however get set to No working issue correctly

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.5-200.fc29.x86_64

**Comment by gioboa** [comment]
Hi, did you press Yes or Yes with comment? Did you have any log in the output?

**Comment by mithrend** [comment]
The message notification does not show at all. This means I cannot press anything. There is no log in the output either.

**Comment by gioboa** [comment]
ok, I try to reproduce the issue and verify. Thanks.

**Comment by probfacile** [comment]
Same here, the message to track time has gone away... tried reinstalling, tried deleting folder and reinstalling... nothing at all

**Comment by mithrend** [comment]
I have also tried re-installing the extention and have tried tracking time mode on "hybrid" and "always".
In both cases worklog minimum tracking time was set to 0

**Comment by gioboa** [comment]
[v 0.15.3](https://github.com/gioboa/jira-plugin/releases/tag/0.15.3) release solved the issue.

**Comment by mithrend** [comment]
Amazing! thank you.
